### ISSUE TITLE
Editor window is bigger than screen

### ISSUE THREAD

**Issue by HeadClot** [rokups/rbfx#101]
Hey I cannot seem to resize my editor window. I have gone ahead and attached the Urho3D.Log

[Urho3D.log](https://github.com/rokups/rbfx/files/3354522/Urho3D.log)

I just opened the editor and there was no ability to resize the window.

Steps to repro

1. Open the editor,

**Comment by rokups** [comment]
You showed me screenshot in chat which displayed an open project. So... Are you experiencing this even in project selection screen?

**Comment by HeadClot** [comment]
Yes - I believe I figured it out. My screen size is 1680x1050

While the editor is setting the screen size to be 1920x1080.

**Comment by rokups** [comment]
Oh so part of the editor window happened to be outside of visible area?

**Comment by HeadClot** [comment]
Yep that is what is happening. I do not know how to resize it though because it is so large.

**Comment by rokups** [comment]
At the moment editor window dimensions are saved in `/path/to/project/.ui.ini`, `Rect=x,y,w,h` value under `[Project][Window]`. Maybe try tweaking that. Meanwhile ill look into adding some logic to avoid creating too big of a window.

**Comment by HeadClot** [comment]
Thanks for the help. Going to tweak that :)

**Comment by HeadClot** [comment]
Ok I managed to resize the window to something a bit more sane. 

https://i.imgur.com/DLAX64k.png

**Comment by rokups** [comment]
Fixed in 4c8a6c4ff1d8245de96480cc857e51302d0a710f.
