### ISSUE TITLE
Does rbfx support being included as subdirectory?

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [rokups/rbfx#103]
The application build just fine when cmake root folder is the rbfx's but eastl and tracy will fail to build when it's the parent folder like:

**cmake root**:
--﹄**myfol**
----﹄**my own thing that links to Urho3D**   
--﹄**rbfx**
----﹄**...**

tracy-* error, desktop, on both static and shared build.
![image](https://user-images.githubusercontent.com/8407331/60764351-11d8d280-a0c3-11e9-8418-d90c106054ff.png)

eastl errors, web (CXX stadard set to 17)
https://gist.github.com/UNDEFINED-BEHAVIOR/898ec07d228c54dc4c873e4ddc1d7a2b

The question is, are this kind of project layout supported? (workaround is quite trivial tho)

**Comment by rokups** [comment]
Not only it is supported - it is primary suggested way to use engine in your project. It gets little testing though. Ill see why this fails and fix it.

**Comment by rokups** [comment]
Here is a sample on how to use engine as subdirectory: https://github.com/rokups/rbfx-sample/

C# part is still broken though.
