### ISSUE TITLE
Editor without settings json

### ISSUE THREAD

**Issue by divinon** [rokups/rbfx#105]
Hello, I found a small problem in the editor when there isn't the editor settings file. In 'Editor::Setup' 'GetDesktopResolution' is called before 'RequireSDL(SDL_INIT_VIDEO)', also setting EP_WINDOW_MAXIMIZE = true will call 'graphics->Maximize' in 'Engine::Initialize', this will immediately spawn a resize event which calls 'Engine::RunFrame' when the flag 'initialized_' is still false, this will fire an assert.

**Comment by rokups** [comment]
Thanks for detailed bug report 👍
