### ISSUE TITLE
Can not rename directories in Resources tab

### ISSUE THREAD

**Issue by nem0** [rokups/rbfx#114]
**Steps to reproduce:**

1. open the editor
2. create a new project
3. in resource tab, try to rename a directory (either with f2 or from context menu)
4. observe f2/context menu is simply ignored

![image](https://user-images.githubusercontent.com/153526/61637885-9cf7c200-ac98-11e9-9243-316bdc30db0d.png)

-----------
**Expected result:**

Option 1: I should be able to rename directories in resource tab.
Option 2:  There should not be an option to rename directories.

-------------
**Note:**
Tested with revision 76c0e3305441e1ccdd305157ac53b3c1ea32e62b, Win10, vs2017

**Comment by nem0** [comment]
Is this dead?

**Comment by rokups** [comment]
Very. I started working on this and one thing led to another and... renaming is quite broken :trollface: And then i got sidetracked with gdb natvis. But we will get there \o/
