### ISSUE TITLE
Thread::IsMainThread() returns false in dynamically linked plugins

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#130]
On VS 2017 (using commit c2a0b2b57103750f22e0f803c26b1f961a6320cf) Thread::IsMainThread() returns false when called from the main thread in code in a dynamically linked plugin

**Comment by rokups** [comment]
I am unable to reproduce this. Please provide more information in what circumstances this api is called and if it really is called on same thread that `Thread::SetMainThread()` is called.

**Comment by eugeneko** [comment]
I wonder if `mainThreadID` is properly initialized when you check it.

**Comment by TrevorCash** [comment]
its not.  I can fix it by calling Thread::SetMainThead()  explicitly somewhere in my plugin code before anything runs.  i set it in the constructor if my newtonphysicsworld class for now.

**Comment by rokups** [comment]
How is your code executed? You aren't supposed to run code before engine is 
initialized.

**Comment by TrevorCash** [comment]
I have TechGame project which links to Urho3D and rbfx-newton.  TechGame is an Application class.  The Engine is initialized first.  Then the physicsworld is attached as a component to the scene.  Its at that point I have to manually set the main thread in the components constructor.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TrevorCash** [comment]
Without setting it.  any events that are fired from the plugin give the events can only be fired from main thread warning

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rokups** [comment]
Main thread is set in [Context::Context()](https://github.com/rokups/rbfx/blob/master/Source/Urho3D/Core/Context.cpp#L149). Put a breakpoint there and see of it executes before your code (it should) and if it executes on the same thread (it should). Judging from your description does not sound like you would be doing something wrong, however something is definitely amiss here.

**Comment by TrevorCash** [comment]
Yeah looks like it is being set in the context constructor before the plugin code:


The thread id does match as well.
First BreakPoint:
![image](https://user-images.githubusercontent.com/2559371/65346172-4ffd7280-db99-11e9-9761-d1607be1f055.png)

Second BreakPoint:
![image](https://user-images.githubusercontent.com/2559371/65346197-5d1a6180-db99-11e9-8b20-aeb5c91fefc8.png)

**Comment by rokups** [comment]
And plugin code breakpoint triggers in main thread but thread I'd variable 
is unset at that point? Did I get that right?

**Comment by TrevorCash** [comment]
Yes.  To Further Test I put a breakpoint here (because of the error message:
![image](https://user-images.githubusercontent.com/2559371/65346538-25f88000-db9a-11e9-86c2-5c10149b07f9.png)

And went into IsMainThread():
![image](https://user-images.githubusercontent.com/2559371/65346622-57714b80-db9a-11e9-8914-7727180d3784.png)

The value for mainThreadID is 0.

**Comment by rokups** [comment]
Maybe put a bp where thread variable is written, maybe even add data 
breakpoint on variable to see where written happen. Maybe something will 
come up.

**Comment by TrevorCash** [comment]
Its is only ever written to once.  Its why I suspect is a linking issue or something.

**Comment by rokups** [comment]
Is address of thread id variable same during context ctor call and during 
plugin code execution?

**Comment by TrevorCash** [comment]
In Context() constructor mainThreadID is indeed set to a number.  however when I break and look at the variable from the plugin side (eg via a call to sendevent) it is always 0.  It is like there are 2 versions of the variable.

**Comment by rokups** [comment]
O was asking about address of variable. Add `&mainThreadID` in watches and break when this variable is accessed, see if address remains the same

**Comment by TrevorCash** [comment]
Yeah the address are different.

**Comment by rokups** [comment]
Now we are on to something. Any chance you build engine as a static lib? Exe and dlls would get different statics and thus you would get what you get.

**Comment by TrevorCash** [comment]
Ah yes it looks like it is being built statically.

**Comment by rokups** [comment]
In static builds plugins are static libs as well. There is wiki article in GitHub on that. https://github.com/rokups/rbfx/wiki/Plugins

So closing as not a bug ;)

**Comment by TrevorCash** [comment]
Ok Thanks, makes sense now - BUILD_SHARED_LIBS doesn't show up as a variable in cmake.  Any chance that could be added with a default value?

**Comment by rokups** [comment]
It's built-in cmake variable that controls lib type when not specified explicitly. Not sure if making an option of it won't create warning. I'll try. And since it's built-in - I don't think it's good ide to switch away to a custom var that does same thing

**Comment by TrevorCash** [comment]
Ah yeah - didn't realize it was a built in thing.  Not a huge deal - I just didn't read the docs..
