### ISSUE TITLE
Crash with CSharp Sample

### ISSUE THREAD

**Issue by mostafa901** [rokups/rbfx#139]
Hi, thanks for the great work, I tried to use this development, from C# entry. but I faced a crash
![image](https://user-images.githubusercontent.com/12208720/68533433-5eb70900-0342-11ea-9c67-d33cf9ee98b6.png)

is there any work around for this?

**Comment by rokups** [comment]
I built everything with `-DBUILD_SHARED_LIBS=ON -DURHO3D_CSHARP=ON -DURHO3D_SAMPLES=ON` and 102_CSharpProject (which is my guess of what you meant by "csharp sample") runs just fine.

You should provide more information on how to reproduce the issue. Isee "rbfx.exe" in the titlebar. Project does not build anything with such executable name.

**Comment by mostafa901** [comment]
weird,... Ok I will start again fresh, and if the case still i will create a repo

**Comment by mostafa901** [comment]
here is how i reproduces it:

- Clone the repo
- change the MakeFile.cmd Line 67 to
`
"cmake.exe -DBUILD_SHARED_LIBS=ON -DURHO3D_CSHARP=ON -DURHO3D_SAMPLES=ON -G "!CMAKE_GENRATOR!" !CMAKE_ARGS! .."
`
- run Makefile.cmd
-Build & debug 102_CSharpProject
- I recieve a warning the need for firewall access,
- I confirm,
and then get the same error.

**Comment by rokups** [comment]
You do not need to change Makefile.cmd. Do `Makefile.cmd -DBUILD_SHARED_LIBS=ON -DURHO3D_CSHARP=ON -DURHO3D_SAMPLES=ON`

**Comment by mostafa901** [comment]
yes that is true. not sure what i have on my system holding this repo from running. the C++ sample  works fine, but the CSharp not

**Comment by rokups** [comment]
Turns out this issue manifests only on windows. I will fix it soonish.

**Comment by mostafa901** [comment]
Perfect, there is a minor issue at [this line](https://github.com/rokups/rbfx/blob/2cc5a6dc646ab448657a3fe7d24e5d1b3b37513b/Source/Urho3D/CSharp/Managed/Script/ScriptRuntimeApiImpl.cs#L141)
this will add the directory path and not the native file path... I proposed a fixation
