### ISSUE TITLE
Embed in WPF

### ISSUE THREAD

**Issue by mostafa901** [rokups/rbfx#141]
Hi,
I tried to embed the GUIwindow into a WPF app. it works fine but the moment I scale the WPF window it crashes.
I created a WPF Usercontrol (uc_rbfx) that will be contained in a WPF Window.
```
public uc_rbfx()
		{
			InitializeComponent();
			try
			{
				System.Windows.Forms.Panel _pnlSched = new System.Windows.Forms.Panel();
				WindowsFormsHost windowsFormsHost1 = new WindowsFormsHost();
				windowsFormsHost1.Child = _pnlSched;
				_Grid.Children.Add(windowsFormsHost1);
				 
				DemoApplication.Parent = _pnlSched.Handle;
				Loaded += delegate
				{
					Task.Run(() =>
					{
						using (var context = new Context())
						{
							using (var application = new DemoApplication(context))
							{
								application.Run();
							}
						}
					});
				};

			}
			catch (Exception ex)
			{
				//Nothing...
			}
		}
```
I get to this error,
![image](https://user-images.githubusercontent.com/12208720/68796703-c1731200-066c-11ea-8118-a3dedd787cab.png)

is there any suggested work around this?

**Comment by rokups** [comment]
Could you zip and share uwp project so i can run a test? Never made uwp app before and it does not seem to be straightforward.

**Comment by mostafa901** [comment]
Sure here is [a repo](https://github.com/mostafa901/WPF_Rbfx.git)
