### ISSUE TITLE
Loading XML scene, doesn't load VariantMap contents

### ISSUE THREAD

**Issue by mostafa901** [rokups/rbfx#143]
if Scene is Saved using this method:
```
                    XMLFile file = new XMLFile(Context);
                    var fileroot = file.CreateRoot("RootNode");
                    _scene.SaveXML(fileroot);
```
it indeed saves all variables with their values to an XML file but when loading to the scene, all variables are successfully assigned back except for VariantMap... I can see the VariantMap is initialized but it is empty.
[a repo is here](https://github.com/mostafa901/rbfx/blob/Issues/Source/Samples/102_CSharpProject/Program.cs)
```
[SerializeField]
public VariantMap Vmap { get; set; }
```

the exportedXML is like this

```
 <component id="5" type="CustomNodeComponent">
      <attribute name="Vmap">
        <variant Key="Comments" type="String" value="testingcode" />        
      </attribute>
 </component>
```

**Comment by rokups** [comment]
Problem with this and some other containers is that during loading we "steal" instance pointer from a `Variant` that is later destroyed. Instead contents should be copied. Assigning to myself.
