### ISSUE TITLE
Creating Model from Scratch

### ISSUE THREAD

**Issue by mostafa901** [rokups/rbfx#146]
I tried to create a model from scratch, but it seems there is something avoiding it from rendering the object, when only you apply Texture. normal color Material works great.

compiling works great. but not the expected results
May you please have a look into this [modelfromscratch](https://github.com/mostafa901/rbfx/blob/Issues/Source/Samples/102_CSharpProject/146_CreatModel.cs)

**Comment by eugeneko** [comment]
FYI:
https://github.com/rokups/rbfx/blob/glow/Source/Urho3D/Graphics/NativeModelView.cpp#L484
You can check how it is different from what are you doing

**Comment by eugeneko** [comment]
I wonder if it would make more sense to check in my commits into master so you can use this code in C#. It's a bit less optimal due to extra allocations and copies, but much more flexible and easier to use.

**Comment by mostafa901** [comment]
Indeed i will do... once i arrive home... will keep you posted.

**Comment by mostafa901** [comment]
did you push it to Master or glow?

**Comment by mostafa901** [comment]
ok found the missing part, Tangent must be identified to allow a face accept texture.
