### ISSUE TITLE
Loading JsonFile doesn't load material

### ISSUE THREAD

**Issue by mostafa901** [rokups/rbfx#149]
I tried saving and loading JSON file. but when loading it doesn't Load the materials

Saving is done like this:
```
        JSONFile jsFile = JSONFile(context_);
        JSONOutputArchive jsonOutputArchive{ &jsFile };
        if (Serialize(jsonOutputArchive))
        {
            return jsFile.SaveFile(destinationPath);
        }
```
implementation:
```
string path = Directory.GetCurrentDirectory() + @"\cube.json";

 SubscribeToEvent(E.Update, a =>
            {
                if(ImGui.Button("Save"))
                {
                    _scene.SaveFile(path);                   
                    Process.Start("notepad++.exe", path);
                }
                if(ImGui.Button("Load"))
                { 
                    _scene.LoadFile(path);
                }
            });
```

**Comment by mostafa901** [comment]
Thanks @rokups now it loads the material. but it seems it crashes,  after closing the engine window.
simply:
**Case 1:**
1. Save to xml, Json  [ binary works fine]
2. close window
it crashes @ line 913 Vector.h

**Case2**
1. Load XML or JSON
2. CLose Window
it crashes @ line 72 Components.cs

**Comment by rokups** [comment]
Seems like this is a different issue. Also lack of stack trace makes report not exactly useful.

**Comment by mostafa901** [comment]
NVM. seems fine now. Thanks
