### ISSUE TITLE
[Windows] C# NuGet package

### ISSUE THREAD

**Issue by RUSshy** [rokups/rbfx#15]
Hi

Is it possible to get NuGet package for C# ?

Ty!

**Comment by RUSshy** [comment]
I can't build the project, it give me lot of red errors, i'm not familliar with c++ and cmake

If no nuget, then is it possible to upload dlls somewhere ? ty!

**Comment by RUSshy** [comment]
![image](https://user-images.githubusercontent.com/18348637/42664260-0f78e010-863a-11e8-9443-372b0187bcd0.png)

**Comment by RUSshy** [comment]
Oh i had to install LLVM 32bit for windows, not 64bit

Now i get this 
![image](https://user-images.githubusercontent.com/18348637/42665571-7e45735e-8640-11e8-9f96-335ad39d4982.png)

**Comment by rokups** [comment]
I am on the last leg of bindings rework using swig. Once that gets merged to master we definitely should do a nuget package.

**Comment by rokups** [comment]
I made an attempt to make a nuget package. It fell short. Could not get msbuild to deploy extra files to needed locations. I might attempt this later, but not for now. Anyone interested is free to help :)

**Comment by rokups** [comment]
We are one step closer to C# nuget package. Way is paved by @gleblebedev by creating [Urho3D.Data](https://www.nuget.org/packages/Urho3D.Data/0.17.0-alpha) package. I plan to use it as a reference to bundle most essential data files in the nuget.
