### ISSUE TITLE
Shadows look terrible in web builds

### ISSUE THREAD

**Issue by rokups** [rokups/rbfx#150]
![image](https://user-images.githubusercontent.com/19151258/69912000-32b41280-142c-11ea-8c47-5f8e068bc97b.png)

**Comment by eugeneko** [comment]
What's the hardware?

**Comment by rokups** [comment]
GTX 1080 + amdgpu driver (linux)

**Comment by rokups** [comment]
rx580 + amdgpu driver (linux)

**Comment by eugeneko** [comment]
Oh, so it's desktop GPU...
This kind of artifacts tend to appear when ppl run Web builds (that are essentialy Desktop) on mobiles.
Maybe OpenGL ES is not properly supported on hardware and drivers?

**Comment by eugeneko** [comment]
Idea for future: treat Web build as mobile unless it is specified otherwise in CMake.

**Comment by rokups** [comment]
Same happens on windows with GTX 1080.

**Comment by eugeneko** [comment]
Can you check samples [here](https://eugeneko.github.io/)?
Do they look in the same way?

**Comment by rokups** [comment]
Same.

**Comment by rokups** [comment]
![image](https://user-images.githubusercontent.com/19151258/119223638-38f7ec00-bb03-11eb-9596-b51ef51d90b5.png)
Now they look ok in your samples, closing.
