### ISSUE TITLE
Strange user interface scale

### ISSUE THREAD

**Issue by carlcc** [rokups/rbfx#152]
![image](https://user-images.githubusercontent.com/12776190/70111050-03034580-168c-11ea-9eef-5e123808eb63.png)

As shown above.

The monitor's physical resolution is 3840x2160
The actual resolution is 1920x1080(System setting.)
System: OS: Manjaro 18.1.3 Juhraya
GPU: Mesa DRI Intel(R) HD Graphics 500 (Broxton 2x6)

If I choose to use 3840x2160, the UI become even more strange.

![image](https://user-images.githubusercontent.com/12776190/70111293-b8ce9400-168c-11ea-913a-44b0286ca8ad.png)

I suspect this was caused by DPI scaling, but I didn't find where the related code is.

**Comment by rokups** [comment]
Yeah DPI scaling is a mess... Dear ImGui does not really support it and editor tried to work around it with limited success. I am working on a PR that implements perfect HDPI support in Dear ImGui: https://github.com/ocornut/imgui/pull/2826. Maybe i should pull in those patches ahead of time into our editor.

#125 related.

**Comment by carlcc** [comment]
Nice!
