### ISSUE TITLE
Generate BoundingBox

### ISSUE THREAD

**Issue by mostafa901** [rokups/rbfx#154]
I tried to generate BoundingBox from Vertices, through:
`BoundingBox.Merge(vertexArray)` and `BoundingBox.Define(vertexArray)` have no effect
`new BoundingBox(vertexArray)` is the only statement gave me correct results.

**Comment by eugeneko** [comment]
Please post code snippet that does not work.

**Comment by rokups** [comment]
```cs
            var arr = new Vector3[3]
            {
                new Vector3(-1, 0, 1),
                new Vector3(-2, 0, 1),
                new Vector3(-1, 3, 1),
            };
            var bb = new BoundingBox();
            bb.Define(arr); // or bb.Merge(arr);
```
Produces expected results. If this is still an issue please post a self-contained testcase reproducing the issue.

**Comment by mostafa901** [comment]
:( it didn't for me 
```
 var v1 = new Vector3(-0.5f, -0.5f, -0.5f);
            var v2 = new Vector3(0.5f, 0.5f, 0.5f);
            Vector3[] vcs = new Vector3[2] { v1, v2 };
            fromScratchModel.BoundingBox = new BoundingBox();
            fromScratchModel.BoundingBox.Merge(vcs);
```
check here a full [repo](https://github.com/mostafa901/rbfx/blob/390b777e59e09f9c96a690e00f1a8c43c7d73358/Source/Samples/102_CSharpProject/155_CreatModel.cs#L162)..

my findings are:
upon instantiating a 'Model' it also instantiate a bounding box with infinity dimensions. so eventually merging infinity to any defined number would be infinity
so since this way failed
```
            fromScratchModel.BoundingBox.Merge(vcs);
```
I decided to create a new bounding box, which will give a zero width and height, then to merge with a defined vertex, but also returned back a zero Height/Width
```
 fromScratchModel.BoundingBox = new BoundingBox();
            fromScratchModel.BoundingBox.Merge(vcs);
```

**Comment by rokups** [comment]
![image](https://user-images.githubusercontent.com/19151258/70864193-704e8a80-1f58-11ea-933c-1c984add89b3.png)
Your code produces exactly expected result as you can see.

**Comment by mostafa901** [comment]
it works if you created a bounding box like this```
var bbx = new BoundingBox();
            bbx.Merge(vcs);
```
and not from an Existing Model like the example I showed in previous message

**Comment by rokups** [comment]
Ohh i know what is going on here. `BoundingBox` is a value type. Doing `fromScratchModel.BoundingBox.Merge(vcs);` copies `fromScratchModel.BoundingBox`, updates it and then discards it. So no issue after all. This is just how C# wrapper on top of C++ works. I am not even sure if it is possible to enable in-place updates.

**Comment by mostafa901** [comment]
so the best way is to instantiate it with Vertices
```
fromScratchModel.BoundingBox = new BoundingBox(vcs);
```
Thanks @rokups

**Comment by rokups** [comment]
Or if you want to update existing bounding box:
```cs
var bb = fromScratchModel.BoundingBox;
bb.Merge(...);
fromScratchModel.BoundingBox = bb;
```

**Comment by eugeneko** [comment]
@rokups I think C# forbids things like `fromScratchModel.BoundingBox.Foo()` for value types. Can we make wrapper behave like native code C#?

**Comment by rokups** [comment]
No idea. Never heard of C# not allowing such usage either.

**Comment by eugeneko** [comment]
@rokups Oh, you are right, it seems it's C# "feature" that has nothing to do with our bindings...
https://rextester.com/FTVS31630

**Comment by mostafa901** [comment]
Well so far this only happen if we are dealing with struct, if struct is
changed to class, every things works as expected.

**Comment by rokups** [comment]
Right. But we want math primitives to be value types for performance reasons. If we changed it's type to `class` it would no longer be free to pass these objects between managed/native boundary. It would involve memory allocations and memory copying.
