### ISSUE TITLE
GenerateTangents() cause memory corruption

### ISSUE THREAD

**Issue by mostafa901** [rokups/rbfx#155]
I tried to generate Tangent througtht this method
```
 Urho3D.GenerateTangents(vb.ShadowData, (uint)vertexData.Length, ib.ShadowData, (uint)indexData.Length, 0, (uint)indexData.Length, 3, 2, 3);
```
it kept running forever, end with memory corruption... I have snipped a code of what i have done, but for a full repo [here](https://github.com/mostafa901/rbfx/blob/Issues/Source/Samples/102_CSharpProject/146_CreatModel.cs).
```
 Urho3DNet.Model fromScratchModel = new Urho3DNet.Model(Context);
            VertexBuffer vb = new VertexBuffer(Context, false);
            IndexBuffer ib = new IndexBuffer(Context, false);
            Geometry geom = new Geometry(Context);

            // Shadowed buffer needed for raycasts to work, and so that data can be automatically restored on device loss
            vb.SetShadowed(true);
            vb.SetSize(numVertices, VertexMask.MaskPosition | VertexMask.MaskNormal | VertexMask.MaskTexcoord1 | VertexMask.MaskTangent, false);
            vb.SetData(vertexData);

            ib.SetShadowed(true);
            ib.SetSize(numVertices, false, false);
            ib.SetData(indexData);

            Urho3D.GenerateTangents(vb.ShadowData, (uint)vertexData.Length, ib.ShadowData, (uint)indexData.Length, 0, (uint)indexData.Length, 3, 2, 3);
```

**Comment by eugeneko** [comment]
This method does not work because you pass nonsense in parameters.
Although, I admit that signature is quite obscure.
You can see how this method is used in the engine itself or you can wait until somebody wrap this function in something more handy.

**Comment by mostafa901** [comment]
Indeed that truly my bad. Apologies.
not sure why I thought of it like that. 
I have revisited it with fresh eyes, and figured it out ... Thanks @eugeneko

**Comment by eugeneko** [comment]
@mostafa901 Just keep in mind that shadow data of IB and VB is read-only buffer. You are not supposed to write there -- it will have no effect on the model's visual.

**Comment by mostafa901** [comment]
I realized that today. infact, I am still mind oriented to C#, which get me confused sometimes. I have created a warper for it on C# and works fine now. I will push later
