### ISSUE TITLE
Seems that I comes too late...

### ISSUE THREAD

**Issue by carlcc** [rokups/rbfx#156]
Sorry to talk about a non-issue problem here.

As described in #152, I finally find out how to fix that, you should scale the ImGui canvas (i.e. io.DisplayScale),  and keep fontScale to 1. Then we will get right DPI scaled interface.

PLUS, The OnRawEvent function, we should multiply context_->GetInput()->GetInputScale(). Or the program behaves trange on macos

Regards

**Comment by rokups** [comment]
Pull from master and test again. I merged my HDPI support PR code to rbfx. Now it should look much better.

**Comment by carlcc** [comment]
Yeah, but seems the scene view and game view looks rough, I suspect you set a view port smaller than the actual visual area size. And the camera orbital control is not available any more : (

I think the solution described above makes more sense. ; )

**Comment by rokups** [comment]
> I think the solution described above makes more sense. ; )

It is not as easy as it looks ;) Dear ImGui works at pixel coordinates. If you scale `io.DisplaySize` x 2 suddenly you have two times more space. You need your custom widgets to take twice as much space. If you were rendering a button with size `{10, 10}` now you need to render it with size `{20, 20}`. Besides this only increases canvas for rendering. Font looks small. There are various knobs to increase font size and you can even get a sharp font with no blurring. It is a hack though. These font settings apply globally and collapse as soon as second monitor comes into play. The biggest issue of all is all kinds of offsets and paddings and what not used by default Dear ImGui widgets. With `io.DisplaySize` x 2 all these paddings and offsets are too small. Some of them can be mitigated by upscaling values in style. Some others can not. So it really is only a half-way solution. Lucky us proper solution is in the works and rbfx is helping to find remaining issues and get it ready to merge into Dear ImGui :bowing_man:
