### ISSUE TITLE
Let Editor work with rbfx installation folder.

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#166]
If I want to edit files of rbfx itself, workspace approach is quite inconvinient.
Can you make rbfx Editor work at least with repository itself, assuming standard resource directories?

**Comment by rokups** [comment]
Test latest master, open bin folder as a project 🤞

**Comment by JSandusky** [comment]
@rokups is it supposed to work out of the box (no edits)? I had to add "Data" to the resource paths of the `Project.json` that was generated in the `bin` folder:

```json
	"resourcePaths": [
		"Resources",
		"Data"
	],
```

**Comment by rokups** [comment]
It should work out of the box (i use "work" _very_ liberally). And `Data` is there: https://github.com/rokups/rbfx/blob/master/bin/Project.json#L14

Note that `CoreData` is not in the list. It is loaded automatically from directory relative to editor binary. Eventually plan is to have files from `CoreData` copied to user reousrces folder on double-click (edit) so you could selectively override files from there.

Aaaand thanks for reminding about unclosed issue ;)

**Comment by JSandusky** [comment]
Ahh, I see what I did. I deleted that from my build-tree while cleaning a mess I made in the bin dir and didn't think anything of it (didn't notice that it wasn't generated when I sat the dir to there). Thanks.
