### ISSUE TITLE
Color editor in inspector is worthless

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#168]
Meh. Yes, this is the edge of physical screen.
![image](https://user-images.githubusercontent.com/8576192/71424518-5a04a500-26a3-11ea-9103-ab3fb13a60ba.png)

**Comment by Lcbx** [comment]
a quick&dirty workaround might be to put the color picker on the left side of rgb values

**Comment by rokups** [comment]
Apparently this is no longer the case, therefore closing.
