### ISSUE TITLE
ImGUI viewport is blurry

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#170]
Maybe 0.5 texel offset is missing? DX9 needs this.
I know we don't need DX9, but it's not removed yet.
Maybe we can just ignore it.

![image](https://user-images.githubusercontent.com/8576192/71424849-4eb37880-26a7-11ea-9b3e-a6d116d89ba7.png)

**Comment by rokups** [comment]
What am i looking at? Seems like normal antialiased shape. ImGui backends handle 0.5 offset when needed.

**Comment by eugeneko** [comment]
> Seems like normal antialiased shape

I don't have antialiasing.

**Comment by eugeneko** [comment]
This is broken for DX11 too. Priority raised.
![image](https://user-images.githubusercontent.com/8576192/71450556-285c0e80-2775-11ea-8ef3-89c8b3da9ca9.png)

**Comment by rokups** [comment]
You really should provide more details. I am unable to reproduce it. Even with DPI scale artificially set to 2.0f viewport is still sharp.

![image](https://user-images.githubusercontent.com/19151258/71511932-c4cd0080-289c-11ea-8303-7591ae32c0f7.png)

**Comment by eugeneko** [comment]
Try 125% scale on Windows.

**Comment by rokups** [comment]
![dx11-125%](https://user-images.githubusercontent.com/19151258/71513845-c39fd180-28a4-11ea-8f04-2d9d9505e20a.png)
Looks fine to me.

**Comment by eugeneko** [comment]
The blurriness of viewport depends on actual viewport size. By scaling viewport I can make it blurry or sharp. Can you try a few different sizes? I also suggest you to use just gray box on black background for testing.

**Comment by rokups** [comment]
Provide exact steps how to reproduce... Come on, you are developer. You should know how to make a proper bug report

**Comment by eugeneko** [comment]
Run Editor with DX11 API and system viewports, with Windows DPI scale equal 125%, with screen resolution equal to 1920x1080.

Place gray box.
Resize window so the client rect aka `rect` in `SceneTab::ResizeMainViewport` is `{ 309, 75, 1195, 462 }`.
`textureSize` should be equal to `{ 1107, 483 }`. Box edges should be slightly blurry.

**Comment by eugeneko** [comment]
I have a suspicion what causes this defect.
In `SceneTab::ResizeMainViewport` we get `rect` already downscaled by DPI and then we upscale it again to get texture size. We may lose some stray pixel there.
