### ISSUE TITLE
Wiki: First Application doesn't work out of the box

### ISSUE THREAD

**Issue by alxgb** [rokups/rbfx#173]
Can't do a PR because this is on the wiki, but since I had to bang my head against the wall for a bit, I figured I'd share so it can be improved.

Not sure how much of this applies to Linux, since I'm using Windows 10 & Visual Studio. However, for that combination:
- The URHO3D_MONOLITHIC_HEADER flag is off by default, but the example code uses the monolithic header for simplicity, so the include just fails.
- The MSVC toolset _requires_ the /std:c++17 flag to successfully compile **entt**. This is true for both the v141 and v142 toolsets (Visual Studio 2017/2019). I had to add this to the provided CMakeLists file contents:
```
# Force CXX standard to C++17, required by some engine components
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
Both options are CMake 3.1.3+, so below the existing 3.4.3 minimum. The entt docs themselves state that C++17 support is **required**, I think it'd be fine.
- The example code seems outdated, it doesn't compile: there's a call to `GetInput()`, which is not defined. Indeed, it seems like this should either be `context_->GetInput()` or what I assume is equivalent (from my limited understanding of the engine so far), `GetSubsystem<Input>()->GetInput()`

Ah, unrelated, but it references the old URL of this repository, and I'm not sure if that's intended or not.

**Comment by rokups** [comment]
I updated wiki page. Thank you for taking time to report this 🙏
