### ISSUE TITLE
Docs/Wiki: C# build/detail reminders (CPU target, scripts, misc)

### ISSUE THREAD

**Issue by JSandusky** [rokups/rbfx#183]
Wiki page for C# should include a mention about `Data/Scripts` loading and using the correct CPU target to match the CMake build (`Any CPU` is an easy `BadImageFormatException`) which are both really easy to overlook when setting up a C# project outside of CMake.

Those are both really easy to overlook time wasters.

**Comment by rokups** [comment]
Admittedly docs/wiki/website situation is a mess... In a sense that info is bit scattered all over and that there arent really up to date docs regarding customizations. We definitely need to work on that. Meanwhile i addressed things you reported. Thanks!
