### ISSUE TITLE
Add optional mipmap rendersurfaces to Texture2D and TextureCube

### ISSUE THREAD

**Issue by JSandusky** [rokups/rbfx#184]
ie.

```
// RenderPath.h
struct URHO3D_API RenderPathOutputInfo
{
	ea::string name_;
	CubeMapFace face_;
	int mipLevel_;
};
```
... instead of  ...
```
ea::pair<ea::string, CubeMapFace>outputs_
```

On DX11 this was trivial, I haven't looked into GL yet but it shouldn't be too difficult.

**Use case:** (1) can now semi-properly do PBR cubemap filtering (2) blur/process mip-chain instead of creating a bunch of textures in a renderpath post-processing.

A more complete use-case (requiring a Reiser model capable preprocessor (like MCPP)), that should probably actually be constructed via code and not hard-wired render-path XML:

```
#define DO_MIP_LEVEL(DIR, FACE, LEVEL) \
    <command type="quad" vs="CubeMapFilter" ps="CubeMapFilter" > \
        <output name="FILTER_CUBE" face="FACE" mip="LEVEL" /> \
        <texture unit="albedo" name="FILTER_CUBE" /> \
        <parameter name="FilterParams" value="DIR LEVEL" /> \
    </command>
    
#define CUBE_FACES \
    X(0, 1.0 0.0 0.0) \
    X(1, -1.0 0.0 0.0) \
    X(2, 0.0 1.0 0.0) \
    X(3, 0.0 -1.0 0.0) \
    X(4, 0.0 0.0 1.0) \
    X(5, 0.0 0.0 -1.0)

<!-- This is an unusual render-path to say the least -->
<!-- Attach it to a `dead` view -->
<renderpath>

<!-- 128 is our source -->
<!-- 64 -->
#define X(FACE, FACEDIR) DO_MIP_LEVEL(FACEDIR, FACE, 1)
    CUBE_FACES
#undef X

<!-- 32 -->
#define X(FACE, FACEDIR) DO_MIP_LEVEL(FACEDIR, FACE, 2)
    CUBE_FACES
#undef X

<!-- 16 -->
#define X(FACE, FACEDIR) DO_MIP_LEVEL(FACEDIR, FACE, 3)
    CUBE_FACES
#undef X

<!-- 8 -->
#define X(FACE, FACEDIR) DO_MIP_LEVEL(FACEDIR, FACE, 4)
    CUBE_FACES
#undef X

<!-- 4 -->
#define X(FACE, FACEDIR) DO_MIP_LEVEL(FACEDIR, FACE, 5)
    CUBE_FACES
#undef X

<!-- 2 -->
#define X(FACE, FACEDIR) DO_MIP_LEVEL(FACEDIR, FACE, 6)
    CUBE_FACES
#undef X

<!-- 1 -->
#define X(FACE, FACEDIR) DO_MIP_LEVEL(FACEDIR, FACE, 7)
    CUBE_FACES
#undef X
    
</renderpath>
```

If there's nothing that screams out as problematic or controversial (the addition of mip surfaces that is, not the use of a preprocessor on a renderpath that's w/e) on I'll ready a PR once I've taken the time to deal with GL.

**Comment by eugeneko** [comment]
If I remember API correctly, all you need is to propagate one extra parameter from render pass to DX calls, right? I don't see any possible issues here.

**Comment by JSandusky** [comment]
Right, DX was easy - I'm pretty sure that OpenGL is going to be roughly the same (just passing an index).

Possibly "*just setup some minimal compute capability*" is more appropriate than exposing mips as RenderSurfaces. I'm not sure compute-less targets (GLES2, DX9) have the oomph to do those filter tasks anyways. The only reason I can think of to expose mip surfaces is for filtering and a compute-device backend could just manage the glue (extra SRVs/UAVs on DX11 - GL is easy). That's the bit that I think is maybe contentious.

**Comment by JSandusky** [comment]
I'm going to go with a minimal `ComputeDevice` instead of abusing the RenderPaths for this. It really feels more appropriate since the reason is to filter cubemaps so PBR can be revisited to be done properly (new light probes are a big help there).

I should be able to have something up for review by the end of the weekend.
