### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by Mac767** [rokups/rbfx#193]
Hi

could you provide c# binary NuGet packages of your engine, please?

Kind regards
Mac

**Comment by rokups** [comment]
Finally a proper nuget package is created. It is still quite minimal, but you already can install it and get `CoreData` + binaries. It is only for .NET 4.7.1 so far, but that will be expanded in the future.

https://www.nuget.org/packages/rbfx.Urho3DNet/0.0.3.1-alpha

**Comment by RayKoopa** [comment]
I just want to tell you how amazing that NuGet package is. Even though I cannot seem to find several parts of the API which is of course still under dev as stated on the wiki, this is a great first pre-release. Hats off and thumbs up!
