### ISSUE TITLE
Wrong window size in Web build

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#194]
When I launch Web build, I have 1280x960 window in browser despite viewport 1024x768

> Set screen mode 1024x768 windowed monitor 0

Image looks blurry, too.
I have 125% DPI scale on my system.
When I set it to 100%, everything looks fine.
Maybe it is browser rescaling content, I don't know. Chrome 80.0.3987.116, x64 bit.

**Comment by rokups** [comment]
Fixed upstream afaik.
