### ISSUE TITLE
WEB is not exported as C++ define

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#195]
Apparently WEB is not exported as define.
Therefore, we may have invalid logics
https://github.com/rokups/rbfx/blob/master/Source/Urho3D/IO/Log.cpp#L237

This code snippet doesn't fire when I build Web.
```
#if defined(WEB)
#error fu
#endif
```
I wonder if other places are broken too

**Comment by rokups** [comment]
Fixed by not using `WEB` define \o/

**Comment by eugeneko** [comment]
Are you sure that `MOBILE` is valid as well?

**Comment by rokups** [comment]
[Yes](https://github.com/rokups/rbfx/blob/master/Source/Urho3D/CMakeLists.txt#L138-L142)
