### ISSUE TITLE
ToggleFullscreen corrupts native UI rendering and many other things

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#198]
Tested with OpenGL on Win10, system UI both on and off.
ToggleFullscreen via Alt+Enter causes UI to disappear.
Also, all existing textures in 3D scene become black.
Also, mouse cursor in samples become stuck in center of the screen when I exit sample while in fullscreen.
Also, now I'm just getting STL assert about magic number.
Moreover, it works just fine in upstream.

Update: even tho I disabled SystemUI in cmake I still get it in the callstack... weird...
Update 2: the fuck?..
![image](https://user-images.githubusercontent.com/8576192/75196094-51e0e880-576c-11ea-8ad7-89a60a0e8649.png)

**Comment by rokups** [comment]
Fixed in 2b4f44e09948074ef5a3c7d98be4a8d6acbf5e38.
