### ISSUE TITLE
Can't build Release SDK version in Visual Studio 2019 Version 16.5.3

### ISSUE THREAD

**Issue by faesong** [rokups/rbfx#204]
Tried latest master 6b9fa3cadd and also same error on earlier 786096a8a commit.

So what I did: run cmake, then open resulting rbfx.sln, try to build Release configuration.

I set this variables: CMAKE_BUILD_TYPE=Release CMAKE_CONFIGURATION_TYPES=Release CMAKE_INSTALL_PREFIX=C:/rbfx-builds/rbfx-release-dist

I have no idea what is this about, hopefully someone can point me towards more info or solutions..

What happens after I run Build in Visual studio:

https://pastebin.com/raw/Emia3H3x (you can see some LINK errors there, search for "LINK" to see errors)

And then if I try again i get this: https://pastebin.com/raw/EfVJXHR1

**Comment by rokups** [comment]
In both instances you are getting:

> cl : command line error D8040: error creating or communicating with child process

Which causes targets to fail building, and later targets can not link to failed ones. Our CI tests with VS2019 and that builds. Honestly i am not sure what to make of it. My intuition tells me it could be broken VS install on your end. But if that was the case you would probably experience same issue with other projects and i assume you do not. @eugeneko any idea?

**Comment by faesong** [comment]
I just tried building Urho3D (some older git version that worked for me before) in release mode, and I get errors too https://pastebin.com/raw/90QEquTB

Something is really strange, looks like I shouldn't have done updates of my Visual Studio install :/

**Comment by faesong** [comment]
Tried building vanilla Urho3D in release mode, just to be sure, and it worked for me.

**Comment by faesong** [comment]
Interestingly, if I switch from /O2 to /O1 the build passes for me

**Comment by eugeneko** [comment]
@rokups I have a feeling that this is internal compiler bug.
All instances of D8040 I can find in Google are all about compiler/environment bug.

@faesong Can you point out what exactly file fails during Urho3D build?
If you have 100% reproducible steps, you can try reporting it on VS dev hub or whatever it's called now.

**Comment by faesong** [comment]
I try again from scratch, trying to right click on Urho3D part and press "Project only => Build only Urho3D", I get this https://pastebin.com/A9pvsgAP

If I lookup this error code, it says it's 

0xC0000005
STATUS_ACCESS_VIOLATION
The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.

Now, I need to find out how to get more data from CL.exe on that error

**Comment by eugeneko** [comment]
Compiler shall not crash regardless of rbfx issues. So, it's worth reporting. They _do_ fix this kind of bugs quickly.

**Comment by faesong** [comment]
Currently I have little idea of what to put into bug report to MS.

One more thing I found out: If I put multithread build **/MP** on, then error is this:
`1>cl : command line error D8040: error creating or communicating with child process`

If I sed multithreaded build to off, then:
    
`1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(507,5): error MSB6006: "CL.exe" exited with code -1073741819.`

Maybe later I find out what and where to report to MS..

**Comment by eugeneko** [comment]
https://developercommunity.visualstudio.com/content/problem/967042/visual-studio-ewdk19577-integration.html

**Comment by faesong** [comment]
MSVC update resolved the issue for me. Hope it's fine if I close it

**Comment by rokups** [comment]
Thanks for letting us know. Meanwhile we switched CI back to VS2017 to avoid such surprises.
