### ISSUE TITLE
generalize find msbuild

### ISSUE THREAD

**Issue by bvanevery** [rokups/rbfx#207]
UrhoCommon.cmake is where msbuild is searched for.  Currently it has a Mono-ism, searching only for a hardwired Mono /current/bin path that is hoped to be correct.  It is not natural for Mono to be installed in a Windows Visual Studio development environment at all.  Some simple case logic is needed to decide what configurations are to be supported.  I am currently using the following to pick up msbuild in my Visual Studio 2017 setup:

```
	if(URHO3D_WITH_MONO)
		find_program(MSBUILD msbuild PATHS /Library/Frameworks/Mono.framework/Versions/Current/bin ${MONO_PATH}/bin)
	elseif (MSVC)
		set(MSBUILD ${CMAKE_VS_MSBUILD_COMMAND})
	endif ()
```
I put a message debug after this and verified that it does in fact pick up the msbuild.

However the logic might not be perfect.  I have assumed that Mono and VS are exclusive concerns.  Someone, may think they are not.  I have also prioritized Mono's version of msbuild.  I read in another issue report that maybe the Mono folks think VS's version of msbuild is to be preferred!  I don't know / care enough about such issues, so hope that "this is how you get started solving the problem", leads you to exactly what you want.

**Comment by rokups** [comment]
Until we implement mono support (#112) conflicts dont really matter. Thank you for finding out about `CMAKE_VS_MSBUILD_COMMAND`, this definitely will improve build experience :+1:
