### ISSUE TITLE
typo PATHS PATHS in UrhoCommon.cmake

### ISSUE THREAD

**Issue by bvanevery** [rokups/rbfx#208]
line 337
`    find_program(SN sn PATHS PATHS`
PATHS is a reserved option for that command.  I don't find anything in CMake documentation saying PATHS is also some environment variable you can just pass unevaluated.  Haven't tested this as I'm pulling my hair out about sn, but pretty sure that's a doubled word typo.

**Comment by rokups** [comment]
Doubling is a typo indeed :+1:
