### ISSUE TITLE
generalize find sn

### ISSUE THREAD

**Issue by bvanevery** [rokups/rbfx#209]
UrhoCommon.cmake has this line for finding sn, the StrongName tool:
```
    find_program(SN sn PATHS PATHS
        ${MONO_PATH}/bin
        /Library/Frameworks/Mono.framework/Versions/Current/bin
        $ENV{WindowsSDK_ExecutablePath_${CSHARP_PLATFORM}}
        ENV PATH)
```
It is noted in another issue that PATHS PATHS is incorrect.  But anyways...
Mono-specific stuff is useless on a typical Windows Visual Studio installation.

WindowsSDK_ExecutablePath_* is also useless.  It assumes that someone will use the Start menu .bat files to create a command line environment in which to run CMake.  In general, that won't happen.  People will run the CMake GUI in no particular environment, and they will run the VS IDE.  The IDE's execution environment is completely different than what you get on a console command line.  That's a "gotcha" of CMake development.

ENV PATH does exist, you can see it in a debug message command.  But there's no reason it will be anything helpful, or desired by the builder.  For instance on my box right now, sn.exe isn't discovered.  It's a tool deeply buried in a Windows SDK, not something that typically gets its own path in a user's environment.

I haven't found any official way in the CMake docs to find out where sn.exe might be hiding.  I think one needs to construct a SDK path using available info.  So far I see that CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION can give a part of a path, for Windows 10 and above, and Visual Studio 2015 and above.  Still working on how to get the rest of a path.

**Comment by rokups** [comment]
What you see there is a shotgun approach in attempt to make it work in as many configurations as possible. It is not ideal since it does require developer prompt, but at least it works in some cases. A better solution would be great, but as you see it is not exactly trivial.

> Mono-specific stuff is useless on a typical Windows Visual Studio installation.

¯\\\_(ツ)_/¯ Mono paths are invalid on on windows, MacOS and windows path are invalid on linux, who cares. They just return no results. I see little point in adding elaborate if/else cascade because end result would be absolutely identical, only expressed in more lines of code.

**Comment by bvanevery** [comment]
They don't just return no results, they feed bogus paths in to the search.  You had             ${MONO_PATH}/bin which if that value is not set, will degenerate to /bin.  Although it may not be trouble, it could be trouble, and generally speaking is bad form.  Similarly inserting PATH from environment at any time, as you don't know what's in the user's path.  These sorts of things can result in hard to track down errors in corner cases that drive users nuts.

Best practice is to understand the appropriate cases and guard them.  

Another reason for minor (not elaborate) if/else cascade is you will not be the only developer.  You want logic to be drop dead easy for others to maintain.  Not guessing how things behave on different systems.

**Comment by bvanevery** [comment]
CMake is proving remarkably resistant to giving up useful info.  Variables I keep examining with debug message statements, are blank.  Also it turns out CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION is not directly useful for deducing a tool path.  It produces numbers such as 10.0.17763.0.  Actual paths where sn.exe lives on my system are:
```
C:\Program Files (x86)\Microsoft SDKs\Windows>dir sn.exe /S
 Volume in drive C has no label.
 Volume Serial Number is A4CD-8D18

 Directory of C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools

11/05/2015  10:25 PM           271,648 sn.exe
               1 File(s)        271,648 bytes

 Directory of C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64

11/05/2015  09:14 PM           319,264 sn.exe
               1 File(s)        319,264 bytes

 Directory of C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools

06/06/2018  10:10 PM           275,584 sn.exe
               1 File(s)        275,584 bytes

 Directory of C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64

06/06/2018  10:17 PM           323,176 sn.exe
               1 File(s)        323,176 bytes

     Total Files Listed:
               4 File(s)      1,189,672 bytes
               0 Dir(s)  31,699,349,504 bytes free

C:\Program Files (x86)\Microsoft SDKs\Windows>

```
I'll go check the various DOTNET things again.

I do wonder whether using sn.exe as a standalone tool is the usual done thing.  As opposed to using project files to sign strong names somehow.  Poking through CMake Issues tracker let me to believe the latter.  And unfortunately, there may be CMake bugs with that.  I am not a C# guy so my understanding of C# project files, toolchains, and expected practices is currently non-existent.

**Comment by bvanevery** [comment]
sn.exe not available on unix #7183
https://github.com/dotnet/docs/issues/7183
> Binary sn.exe is not provided by .Net Core SDK 2.1.302 on unix (but it is by mono...)
> IMHO dotnet/cli should be a standalone replacement for mono (when migrating to netstandard2.0/netcoreapp2.1) so needing mono to get the sn.exe binary to be able to sign seems odd to me...

**Comment by rokups** [comment]
Ouch. Reasons to not support .net core are piling up it seems.

**Comment by bvanevery** [comment]
Other bug tracker items have talked about adding local signing capability to SignTool and got merged in.  I think it is possible that you are doing things in an old fashioned way, with sn.exe.  However learning those details has not been my objective.  I was looking for better CMake examples, since there is some CMake in the dotnet repo.  At least now I understand that sn.exe lives somewhere in the dotnet Arcade, a shared pile of stuff for many Microsoft projects.  Not sure yet if its code is in there, or it merely gets copied to there via NuGet.  Maybe the Arcade will tell me how sn.exe becomes installed on systems.  Maybe I'm just insane to stare at something as complicated as those repos to figure this out.  But I've stared so long at the CMake docs without results, that it isn't any _more_ insane.

**Comment by bvanevery** [comment]
https://github.com/rokups/rbfx/commit/360b897f22f8b5176c67b2c38e4bd37845cedddb
eliminates sn.exe.  Not sure if that's the nice way to reference it.  Pulled the code, tried it in CMake GUI, out-of-source build, all default settings, except I put check in URHO_CSHARP checkbox.  CMake configures and generates .sln files.  They build without error, about 2.5 hours on an old laptop.

Trying to run a debug x64 version of Editor does result in an error dialog box.
> Tracy profiler initialization failure
> CPU doesn't support RDTSCP instruction
Then debugger opens Urho3DPINVOKE.cs at line 105:
`static SWIGExceptionHelper() {`
Nasty MS dialog box:
> Managed Debugging Assistant 'LoaderLock' : 'Attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.'

Do not know if bug is related to removing sn.exe.  Suspect not.  Likely my laptop is old, code makes unwarranted assumption that RDTSCP is available at runtime.  Likely independent issue.  Defer to Rokas' judgment whether to close this.

**Comment by rokups** [comment]
Definitely independent. I have seen this in the past on a MacOS VM, however fix was to enable this instruction in VM settings. Tracy assumes presence of RDTSCP on x86 platforms. If you may disable profiling with `-DURHO3D_PROFILING=OFF` or if you need that you may poke around `TRACY_HW_TIMER` define in tracy files and add knobs to disable it.
