### ISSUE TITLE
need dependencies for generated CSharp files

### ISSUE THREAD

**Issue by bvanevery** [rokups/rbfx#211]
> 1>C:\devel\build\rbfx\Source\Urho3D\Urho3DCSharp\ProfiledMutex.cs(66,87,66,104): error CS0117: 'Urho3DPINVOKE' does not contain a definition for 'new_ProfiledMutex'
> 1>C:\devel\build\rbfx\Source\Urho3D\Urho3DCSharp\ProfiledMutex.cs(70,19,70,40): error CS0117: 'Urho3DPINVOKE' does not contain a definition for 'ProfiledMutex_Acquire'
> 1>C:\devel\build\rbfx\Source\Urho3D\Urho3DCSharp\ProfiledMutex.cs(74,30,74,54): error CS0117: 'Urho3DPINVOKE' does not contain a definition for 'ProfiledMutex_TryAcquire'
> 1>C:\devel\build\rbfx\Source\Urho3D\Urho3DCSharp\ProfiledMutex.cs(79,19,79,40): error CS0117: 'Urho3DPINVOKE' does not contain a definition for 'ProfiledMutex_Release'

Also numerous warnings in many files of the form:

> 1>C:\devel\build\rbfx\Source\Urho3D\Urho3DCSharp\Skybox.cs(49,61,49,71): warning CS0168: The variable 'handleType' is declared but never used

Currently leaving URHO3D_PROFILING=ON is not a workaround on machines that lack the RDTSCP instruction, as Tracy's use of it causes the Editor to throw an exception.

**Comment by rokups** [comment]
Delete `C:\devel\build\rbfx\Source\Urho3D\*CSharp` folders and regenerate cmake cache

**Comment by bvanevery** [comment]
Deleted the \ImGuiCSharp and \Urho3DCSharp folders.  Didn't see any other *CSharp folders. Closed VS, even if that may not have been strictly necessary.  In CMake GUI, selected "File.. Reload Cache", then hit Generate.  Clicked on .sln to open VS.  Right click on **ALL_BUILD** and selected Build.

Seems to only be building the CSharp wrappers, instead of the whole .sln, which is a good thing.  This could nevertheless be some time, until I have a result.

A more robust dependency calculation, would be desired when CMake options change.  As users will change them, and will then believe in the brokenness of the build, rather than knowing of this special step to take.  Back in the day, I remember that providing clean targets or dependency targets for generated files or folders, was an obscure bunch of hoops to jump through.

**Comment by rokups** [comment]
Right, this is a sore point i did not really know how to solve. Problem is that we do not know beforehand what files SWIG will generate. Do you have any idea how to implement dependency tracking in this particular case?

**Comment by bvanevery** [comment]
Once upon a time I implemented a multi-stage bootstrap for the Chicken Scheme-to-C compiler.  Just about anything can be solved if it's broken into enough stages.  Without analyzing the the problem, or remembering how to do it, I do know it can be done.  It's just work, and I don't remember how much.  I can look into it at some point.

Right now it is not a blocking issue though.  The blocking issue is Tracy polluting end user runtimes, causing machines such as mine to crash in the wild.  If Tracy is only in a Release With Debug Info style build, then this dependency issue is not immediately front-facing to developers.  It only becomes apparent when someone decides they really need to do some profiling.  So for triage, perfect dependency tracking becomes less pressing.  Ergo, I am far more focused on winning the battle of where Tracy is and isn't supposed to exist, in a sane universe.

**Comment by rokups** [comment]
Any idea whether we can check if cmake config has changed since last time? If so - we could simply be deleting those files and force regeneration of bindings. Deleting them on each reconfigure would be too much however.

**Comment by bvanevery** [comment]
I'm sure there's a way, and it is best to handle it in as fine grained a way as possible.  Since you said you're dealing with things you "do not know beforehand", I am supposing you're doing some kind of GLOB.  Which always makes propagation of dependencies a problem, which is why Kitware recommends against using it.

However if you're not being lazy and truly don't know, then you don't know.  I remember dealing with such things by using CMake to run CMake itself as a scripting language to get results.  Such techniques are error prone and you have to know all the differences between command line environments, CMake environments, and VS enviornments.  They're not the same.  I did make it all work, but that was 14 years ago.  This sort of thing can be done again, but it's effort.

Triage is for Tracy with RelWithDebInfo.  No further "research" effort on this issue until then.  No point working on shifting sand.

**Comment by bvanevery** [comment]
Final note: back in the day, I wrote custom build suffix rules to create dependencies at file level of granularity.  But whether you can do that with SWIG, depends on whether it does things file by file or all in one massive output.  I have not studied its theory of operation.

And at this point I don't plan to.  You will, unfortunately, be working on this yourself, or whomever else you can get to take it on.  I am done with rbfx.  These various issues create lots of work for me, with too many steps to get to my actual agenda: a geometry manipulation language.  If I had confidence in your release and project management skills, I would continue.  But I think what you want, is to do active development, as mainly you alone see fit.  I don't see you attracting more developers.  I see it pretty much staying as you + a sidekick or two.  In a few years you will either have something public facing, that people have heard of, or you won't.  Good luck.
