### ISSUE TITLE
Tracy should default to OFF in Debug and Release builds

### ISSUE THREAD

**Issue by bvanevery** [rokups/rbfx#212]
From the Tracy manual, page 8:
> The application you want to profile should be compiled with all the usual optimization options enabled
> (i.e. make a release build). It makes no sense to profile debugging builds, as the unoptimized code and
> additional checks (asserts, etc.) completely change how the program behaves.

Tracy currently is part of Debug builds on VS.  On machines that lack the RDTSCP instruction, this causes Editor to throw an exception.  Such machines do exist in the wild, so this is a harm.  Debug builds are also typically the 1st thing a person evaluating a codebase sees when firing up CMake.  It looks completely unprofessional to have Editor die, and there's no profiling benefit.

I think it likely that Tracy should not be enabled by default at all, for any build.  However I'm still studying its theory of operation.  Avoiding this in a Debug build, is at least a straightforward decision, as there is no benefit and only liability.

**Comment by bvanevery** [comment]
Documentation indicates that Tracy is a dangerous and not end user facing tool.  It should only be used by developers.  Page 9, my emphasis in bold:

>2.1.2 On-demand profiling
By default Tracy will begin profiling even before the program enters the main function. If you don’t want
to perform a full capture of application life-time, you may define the TRACY_ON_DEMAND macro, which will
enable profiling only when there’s an established connection with the server.
It should be noted, that **if on-demand profiling is disabled (which is the default), then the recorded events
will be stored in the system memory until a server connection is made and the data can be uploaded9.
Depending on the amount of the things profiled, the requirements for event storage can easily grow up to
a couple of gigabytes.** Since this data is cleared after the initial connection is made, you won’t be able to
perform a second connection to a client, unless the on-demand mode is used.

Current release of Tracy is version 0.6.3.  Numbering does _not_ suggest confidence in robustness for an end user.  Things will go wrong.

**Comment by eugeneko** [comment]
@rokups How about setting Tracy off by default but keeping in on in CI?

**Comment by bvanevery** [comment]
https://github.com/wolfpld/tracy/blob/master/NEWS
From the Changelog:
>Note: There is no guarantee that version mismatched client and server will
be able to talk with each other. Network protocol breakages won't be listed
here.

This is release suicide.  It might be reasonable to have it as part of a "Release with Debug Info" style of build.  I don't see any other case use where this should even remotely be considered as a default.

**Comment by bvanevery** [comment]
Page 25 of the manual indicates Release with Debug Info is the sane way to be using the tool:
>Debugging symbols:
To have proper call stack information, the profiled application must be compiled with debugging
symbols enabled. You can achieve that in the following way:
• On MSVC open the project properties and go to LinkerDebuggingGenerate Debug Info, where
the Generate Debug Information option should be selected.
• On gcc or clang remember to specify the debugging information -g parameter during compilation
and omit the strip symbols -s parameter. Link the executable with an additional option -rdynamic
(or --export-dynamic, if you are passing parameters directly to the linker).

**Comment by rokups** [comment]
> @rokups How about setting Tracy off by default but keeping in on in CI?

Possible, but i am not sure whether we should do it.

It probably should be off in debug builds, although even then profiling support is somewhat useful sometimes.

I am not sure it should be off by default in all builds however. This software is primarily aimed at developers. Assumption is that developer will be able to recompile his software with desired settings. Most of the time is spent developing software, and release is just a final step, therefore build settings are aimed at developers, not users. It is developer's responsibility to decide build settings for final release package.

I suppose a middle ground could be `-DURHO3D_PROFILING=RelWithDebInfo` by default, with ability to configure profiling for multiple build configurations if desired.

**Comment by eugeneko** [comment]
> This software is primarily aimed at developers. Assumption is that developer will be able to recompile his software with desired settings.

I assume that default settings shall offer the best _stability_ first and foremost.
If developer wants to enable some potentially harmful feature, it's their choice and it should be explicit. Otherwise you are enabling developers to leave default options during the release.

I have never bothered to disable profiler because I assumed it's almost zero cost feature (like profiler in vanilla Urho). Apparently it's not.

**Comment by rokups** [comment]
It is zero-cost. Honestly - @bvanevery is very much an edgecase. Laptop with no RDTSCP and i suspect 32bit as well. It is a miracle that laptop still works. According to steam hardware survey 32bit systems are insignificant minority already. While i do think we should make it work on old hardware if possible, i definitely do not agree that it should be done at cost that users with better hardware would have to pay.

**Comment by bvanevery** [comment]
Suspicion is wrong, it's a 64-bit laptop from 2008.  It is also a machine that's running current Windows 10 just fine, so "miracle" or not, it's an actual modern platform.  Generally the way you get a working Windows 10 machine out of an old Windows 7 or 8 machine, is installing a few drivers from the Windows 8 era.

Failure to try to detect RDTSCP at runtime is basically irresponsible.  That doesn't just blow up for a developer, that blows up for an end user, a person playing a game.  That's non-zero business cost to someone trying to use the engine to make money.  So's consuming 2GB of RAM _by default_.  The blowup stories aren't going to end at these 2 things I already found.  Do you want to take bets on how bad the Ryzen CPU slowdowns were?

What telemetry capability is so important, that you think end users are supposed to be exposed to the Tracy active development risk?  It's a 0.x.x release for the past 3 years, and the project doesn't even have "major minor patch" stability discipline.  You're listed as a Tracy contributor, Rokas, but you aren't keeping up with development.  You're 1 minor release behind official releases, and 2 behind Master.  So how do you assert zero cost?

A developer wanting a profiling tool, I get.  End users shouldn't be seeing that in a stable production build.  Which is what Release means.

**Comment by rokups** [comment]
End users should not be exposed to tracy. It is developer's responsibility to take care of that. But you are right, tracy should not assume RDTSCP is present on all x86-based platforms.

**Comment by eugeneko** [comment]
> End users should not be exposed to tracy. It is developer's responsibility to take care of that

For me, "default option" means that it's 100% safe to use the engine in this state, both by developer and by user.
And if I want some fine tuning or performance/memory optimization, I can change that option to non-default value.

If "default" option is not 100% safe for both developer and user, it's responsibility of the _author_ to somehow deliver this information to every single developer using the library.

**Comment by bvanevery** [comment]
> End users should not be exposed to tracy. It is developer's responsibility to take care of that.

It is also your responsibility as project organizer not to push "exploding" technologies by default.  If default settings determine intent, your politics would seem to be to force everyone to experiment with Tracy being active by default.  Or even more generally, that everyone should be profiling by default.  Why should URHO3D_PROFILING be default?  Other than you thought it was convenient for your building on your own box.

When someone comes along to evaluate rbfx, what they may _actually_ see from these default choices, is "My stuff explodes in your face."  And many will not go to the level of effort I did, to actually RTFM for Tracy, figure out what the heck it is, look at its Changelog, and look at what version rbfx is using.  That's _work_.  Many will not do that work.  They will just conclude, with some justification, "This project is broken, they don't know how to release code" and move on.

I don't want to be fighting uphill adoption battles, about whether developer facing stability actually matters.  I hope we can get on the same page about that _real quick_, because I do not plan to make a habit of looking over someone's shoulder about what professional release practices are.  This would not even be a discussion in industry.

I'd like to hear why telemetry is supposed to be a mission critical feature for rbfx.  In industry, people make serious cases for that kind of thing.  They don't just throw it over the fence and call it good, let alone with a pre-1.0 release for the tooling.

Absent mission criticality, Tracy shouldn't be a default.  It should be in Release With Debug Info, where such things belong.  Not sure how the Unix crowd wants to culturally handle that, as they used to be weird about -O -g.

**Comment by eugeneko** [comment]
I’m not sure about Tracy enabled by default on RelWithDebInfo too.
This configuration is used for final release builds too.

We use it on my day job to get nice dumps when our app crashes on user’s
machine.

пн, 4 мая 2020 г. в 17:53, bvanevery <notifications@github.com>:

**Comment by rokups** [comment]
It would be your job to disable profiler in such builds.

On the topic of nice dumps - i have my eye on breakpad for a while. It should be implemented for those nice dumps. It splits debugging info from executable (less relevant in case of windows/pdb) and nice stack traces can be reconstructed later.

**Comment by bvanevery** [comment]
>I’m not sure about Tracy enabled by default on RelWithDebInfo too.

I think having Tracy by default is reasonable in such builds, as that's where Tracy is supposed to live, per its manual.  I think having Tracy pushed to devs _somewhere_ is a good idea, as otherwise it doesn't get any kind of real world testing in rbfx.  But there should also be an easy switch to remove it entirely from the build.  Some devs may not want the complication of Tracy at all.  When I RTFM, it was a rather complex programming model, with many concerns that will blow up in your face.  The cross-platform fragility is particularly startling, due to "security" issues quite beyond the author's control.  It's a good manual, and it makes it clear this stuff is _not_ a kiddie ride.  You're responsible for swinging a chainsaw around.

**Comment by bvanevery** [comment]
I am thinking flags should be something like:
TRACY_FOR_RelWithDebInfo ON
TRACY_FOR_Release OFF
but I won't swear to exact nomenclature.  Perhaps \_FOR\_ is redundant.  Terms might also be too VS-y.

And no support for Debug build.  I've wondered how someone debugs Tracy itself though, but can't they just use RelWithDebInfo for that?

**Comment by nem0** [comment]
No profiling debug builds is deal-breaker. I had to profile a debug build just yesterday.

**Comment by bvanevery** [comment]
Ok, a flag such as TRACY_Debug OFF by default, is no more difficult than any other scenario.  But can you explain to me what Tracy is supposed to provide you in a Debug build?  It can't provide you accurate timing information.

**Comment by nem0** [comment]
It can and it does provide accurate timing in debug build. If something is unbearably slow in debug build it's simply unusable for developer who needs to run debug build and profiling is the way to find out what's the culprint.

**Comment by eugeneko** [comment]
Never thought I'd say it, but I agree with @nem0, I do profile debug builds, probably as often as release ones.

**Comment by rokups** [comment]
In that case disabling profiler in debug builds by default makes little sense.

Good news is that new version of tracy uses `RDTSC` instead of `RDTSCP`, so it should no longer crash even on old hardware.

**Comment by bvanevery** [comment]
I have not researched the use of RDTSCP vs. RDTSC in current Tracy (0.6.3 stable or 0.7.x master?).  I do know they are not equivalent in utility, that there are reasons why people would want to use 'P'.  I don't know if they matter to Tracy's accuracy.

Rokas I am guessing you haven't kept up with Tracy's development, because it doesn't have a CMake build.  People have requested that feature a few times: https://bitbucket.org/wolfpld/tracy/issues/85/cmake-support https://github.com/wolfpld/tracy/issues/2  In the latter entry, 2 people seem to have partial results.  wolfpld said:
>If you are willing to document it in the manual and keep support it later, then sure, go ahead.
>
>Just don't change the existing build system. 

So you are probably trying to avoid becoming Tracy's CMake buildmaster, as that seems to be the price of admission.  And I will say from previous experience, having the project lead *not* personally committed to CMake, is not a good position to be in, nor a good endgame.  Once upon a time I lost 1 man year of my life that way, fair warning.  Back then CMake was less accepted as standard drill though, and the project lead wasn't committed to Visual Studio either.  Still the problem remains of a dev lead who serves _2_ masters: whatever their current build is, and CMake.  It's not a good position to be in.  Lead tends to break whatever's in your CMake build.  Carelessness in that regard eventually causes a reckoning (my endgame), lead then junks your CMake build.

Anyways that's a long way of saying it didn't look trivial to swap rbfx's current Tracy for newer.  But you surely know how you've done things better than I.

I also say Tracy has many risks apart from RDTSCP, that will always be ongoing, and should not be end user facing by default.

Nor should Visual Studio have it in Debug by default.  When someone evaluates a CMake-based open source project for the 1st time, the Debug build is the 1st thing they ever see in action.  _When_ Tracy does something crazy (not if), that person sees a broken build and moves on.

For build options, my current thinking is to handle Visual Studio only and wait for other people's input on other toolchains.  I'm not set up to test other things anyways.  I would have as defaults:

TRACY_VS_DEBUG OFF
TRACY_VS_RELEASE OFF
TRACY_VS_RELWITHDEBINFO ON
TRACY_VS_MINSIZEREL OFF

Although I don't see any MinSizeRel in my VS for some reason.  Haven't solved it in 10 minutes, moving on.

**Comment by nem0** [comment]
RDTSCP is slightly faster than RDTSC, but the difference is totally irrelevant for something like game engine profiler. Integrating Tracy in a project is also totally trivial, I did it for non-cmake-based project, the build-integration part took a few minutes. 

I totally agree that new users must have as painless experience as ever. I've seen users gone for much smaller issues. However no profiler (even if it can be turned on, optional features are easily overlooked) is also a problem.  Either Tracy is good enough to be enabled by default or it's not good enough to be used at all. If someday an rbfx binary or nuget is distributed, will it have no profiler?

**Comment by bvanevery** [comment]
> Either Tracy is good enough to be enabled by default or it's not good enough to be used at all.

That is clearly not the dichotomy.  Tracy is currently at a pre-1.0.0 release after 3 years of development.  Assuming its lead developer does most of the work, he's made no commitment to "patch" release number stability.  Rather, he throws in whatever he wants to do next, in the style of active development.  He wrote a great manual indicating what a power saw Tracy is, fully capable of cutting off your fingers in all sorts of ways.  The value proposition of Tracy, is saving you from having to spend $8000 on a mature commercial grade tool, _if you know what you're doing._  It has a role.  It shouldn't be a "first thing you ever see in rbfx" role.

There is a difference between making Tracy available so that the programmer _can instrument things themselves_, and rbfx _insisting on its own telemetry_.  I haven't even looked at the latter case.  If it's a problem when Tracy is turned ON, then I would seek to minimize its footprint and impact.  Especially if it triggers a rebuild when activated.  But those are subjects for separate Issues.

My concern is making sure that Tracy has _no role whatsoever_ in a _brand new user's_ experience.  The new user's build (i.e. Debug) **must work**.  That's how you attract new developers to a project.  If a build works, then the devs know what they're doing.  That's the impression to be created.  Gratuitous displays of competence, early and often.

If a new user wants to RTFM and start tooling their own code with Tracy, to solve their own problems, that's fine and shouldn't be prevented.

**Comment by nem0** [comment]
> he throws in whatever he wants to do next, in the style of active development

That's how 99% of the OSS is developed, including rbfx and most 3rd party dependenices.
Profiler is essential tool for most real games, I've not worked on a game which did not require a profiler. Disabling it by default because it does not work properly, only to let users find out much later that it does not work is cheating the users and is much more annoying than breaking immediately on start. At least as a user I immediately know what I can expect and not spend hours with the engine to find out all the issues.

RDTSCP problem is fixed in latest Tracy, so it's no longer an issue. And if you still want to disable Tracy because of its low quality, you would have to disable some more, starting from e.g. Assimp.

**Comment by bvanevery** [comment]
>> [Tracy's primary author] throws in whatever he wants to do next, in the style of active development
>
> That's how 99% of the gamedev OSS is developed, including rbfx and most 3rd party dependenices.

It's also "99%" garbage of no use to anyone else, because these people are amateur hour.  I'm not planning to work on such a project.  Learned my lesson about devs who throw things over the fence a long time ago.

> Disabling it by default because it does not work properly, only to let users find out much later that it does not work is cheating the users and is much more annoying than breaking immediately on start.

I am not prepared at this time to hold a referendum on Tracy as compared to other profilers.  You can profile stuff in Visual Studio already.  I don't know about other toolchains and platforms.  Tracy is advertizing specific capabilities.  Rokas seems to think well enough of its capabilities, to have contributed in at least a modest way to its development, and to get it CMake integrated in rbfx where no CMake build naturally exists.  Or will exist, for some time, if at all.

My project goal is whether _rbfx_ works.  Not whether Tracy works.  There are lots and lots of things that rbfx still needs, to be taken seriously in public.  There are projects like Godot out there with more money, better marketing, more developers working sustainably, and way more mindshare, than rbfx has got.  That means you have to make correct decisions on execution every step of the way, if you hope to keep up and surpass.  As opposed to completely wasting everyone's time with amateur hour.

I've been watching amateur hour on Urho3D for 5 years.  I finally stepped up when my own needs "could rationally align" with those of open source.

> RDTSCP problem is fixed in latest Tracy, so it's no longer an issue. 

Not true until that code is _in rbfx_.

> And if you still want to disable Tracy because of its low quality, you would have to disable some more, starting from e.g. Assimp.

One thing at a time.  _Assimp_ hasn't blown up in my face yet.  I haven't RTFM and scoured the Changelog of Assimp to find out how likely it is to blow up in everyone's faces.  Tracy, I've done the homework.

**Comment by nem0** [comment]
> You can profile stuff in Visual Studio already.
VS has a sampling profiler and while it's useful to profile certain kind of issues, it's completely useless (because of its sampling nature) to profile other issues. Every single gamedev project I worked on in the last 15 years used such profiler. It's one of the basic tools engine needs. 

Note: I'm not trying to persuade anybody to use Tracy in rbfx, I'm not rbfx stakeholder. I'm just pointing out 3rd party developer perspective.

**Comment by rokups** [comment]
> If someday an rbfx binary or nuget is distributed, will it have no profiler?

I intend to publish nuget built as `RelWithDebInfo` and it will include everything, profiler included.

> > RDTSCP problem is fixed in latest Tracy, so it's no longer an issue.

> Not true until that code is in rbfx.

https://github.com/rokups/rbfx/commit/0e0e9a9755280e49b70bb77a1f70f161e6bba7eb


Now that we established that profiling is definitely useful in debug builds as well - i see little reason to change anything on the build system side. Default build is a demo pretty much, it is not meant to be a configuration that end users will be using. Simply because there can be so many different projects with different requirements and there just is no one-size-fits-all configuration. People who do not need profiler will have to disable profiler. People who do not need physics will have to disable physics. Profiler is a good demo however, so we definitely must keep it even if for showing off.

**Comment by bvanevery** [comment]
> Now that we established that profiling is definitely useful in debug builds as well - i see little reason to change anything on the build system side.

You have an unwarranted faith in the stability of Tracy.  I have repeated myself enough times in this thread.  The message of developer facing stability, for adoption, is not something you value.  I'm afraid I can't work with you.  I can save myself a lot of work, for my own agenda, by not dealing with how you are choosing to do things.  Good luck with rbfx.
