### ISSUE TITLE
(SDK-only?) faulty #include<Tracy.hpp> present when configured with URHO3D_PROFILING=False 

### ISSUE THREAD

**Issue by faesong** [rokups/rbfx#213]
I think the fix is to surround the include with `#if URHO3D_PROFILING`

https://github.com/rokups/rbfx/blob/master/Source/Urho3D/Core/Profiler.h#L25

**Comment by rokups** [comment]
We do not have wrapper macros for all of tracy's features. I think right way would be to include tracy header SDK even when profiling is disabled, so that user code using these macros would not break when building without profiling.
