### ISSUE TITLE
libGLEW SIGABRT

### ISSUE THREAD

**Issue by astlin** [rokups/rbfx#230]
I'm new to rbfx. Built with no problems but starting Editor got SIGABRT signal with message:

`free(): invalid pointer`

Rebuilt in DEBUG mode and found out that problem is in the glew.c at line 13380

`free(extStart);   // rbfx: Fix memory leak.`

Commenting out this fixes the problem.

**Comment by rokups** [comment]
What platform did you test on? I suspect we are facing an inconsistent driver behavior.

**Comment by astlin** [comment]
Ubuntu 20.04 x64. Nvidia 450.80.02 drivers.

**Comment by rokups** [comment]
This change was reverted a while back.
