### ISSUE TITLE
How to start the Editor

### ISSUE THREAD

**Issue by Lcbx** [rokups/rbfx#238]
I built the repo using the Makefile.cmd as suggested in #70 

It seems to have ran successfully :
![image](https://user-images.githubusercontent.com/10773384/99295677-03b5cd00-2846-11eb-95f8-8b04907786d5.png)

However there is no exe generated. Am i missing something ?

Config is :
Windows 10 on a x64 architecture
cmake and msvc 2019 installed

**Comment by eugeneko** [comment]
Did you actually build the repo or just configured it?

**Comment by Lcbx** [comment]
So the makefile only configures... It says 'Build succeeded' so I thought it also builds.

Indeed, I needed to run the command `$ cmake --build ./cmake-build`

Thanks @eugeneko
