### ISSUE TITLE
Build editor with C# components

### ISSUE THREAD

**Issue by Lcbx** [rokups/rbfx#241]
When I build the engine with
```
$ cmake -DURHO3D_FEATURES=CSHARP .
$ cmake --build .
```
The Editor is built too, but there's no C# script component in the component menu.
What am i missing ?

-- Also, an off-topic question : since the editor does not need to be recompiled to be used with C# as the scripting language, could it be made into a github release ?

**Comment by rokups** [comment]
Hey @Lcbx,

```sh
cmake -DURHO3D_FEATURES=CSHARP .
cmake --build .
```

For starters, this is very wrong. You are building everything in source code directory. That is a recipe for disaster. Do something like:

```sh
git clone https://github.com/rokups/rbfx.git
mkdir rbfx-build
cd rbfx-build
cmake -DURHO3D_FEATURES=CSHARP -DURHO3D_ENABLE_ALL=ON ../rbfx
cmake --build .
```

Note that i also included `-DURHO3D_ENABLE_ALL=ON` which enables all features. C# is very experimental and does not (or should not, im surprised you built it) compile in partial config. This would also enable `URHO3D_PLUGINS` which is required for runtime-compiled C# scripts to work.

When all that is done and you create a new project in editor, put your C# components to `/path/to/project/Resources/Scripts` and it should show up in components menu.

**Comment by Lcbx** [comment]
Hello @rokups,
thanks for the reply :)

I tried what you suggested but there was no executable at the end of build (and no error during it).
I played with enabling/disabling features using cmake-gui with no luck either :/

**Comment by rokups** [comment]
I forgot that C# targets need restoring as well. Failure to do so ought to give you build errors though. Try:
```sh
git clone https://github.com/rokups/rbfx.git
rm -rf rbfx-build
mkdir rbfx-build
cd rbfx-build
cmake -DURHO3D_FEATURES=CSHARP -DURHO3D_ENABLE_ALL=ON ../rbfx
cmake --build . --target restore && \
cmake --build . -j8
```
Restore fails on my machine however, and i am not sure why. It works on CI though. Something to be investigated.

**Comment by Lcbx** [comment]
ok so restore highlighted that i did't have the .Net 4.7.1 SDK installed,
but once that was dealt with, It worked !

Thanks for the help !
Might post something in the urho3d forums if my experiments lead to something interesting. Have a nice one ;)
