### ISSUE TITLE
PhysicsWorld class not available in C#

### ISSUE THREAD

**Issue by Lcbx** [rokups/rbfx#243]
Heya

I'm remaking the IK example in C#  for practice but 
![image](https://user-images.githubusercontent.com/10773384/101267582-7f76ab80-375a-11eb-898a-59b8977ef431.png)

`PhysicsWorld` is not defined but `PhysicsWorld2D` is. That's weird.

Looking a bit further I checked that I had `URHO3D_PHYSICS=ON`. No problem on that side.

Then I discovered this  in `Urho3d.i` (the swig interface file) :
![image](https://user-images.githubusercontent.com/10773384/101267689-cf09a700-375b-11eb-9b40-4c0754c04934.png)

Seems like Physics stuff was commented. I uncommented it and now, it seems to work.

Is there a reason for leaving the C# Physics section commented?

**Comment by rokups** [comment]
There was some work in progress on newton integration, so i thought we might switch eventually and avoided touching physics bindings. That is clearly not happening. Physics bindings need some cleaning up. I bet they generate plenty of `SWIGTYPE_*` classes. But other than that, there should be no other issues.

**Comment by Lcbx** [comment]
Awesome, I was scared it was broken :)

Personally I'd say [Bullet is good enough in most cases](
http://www.adrianboeing.com/pal/papers/p281-boeing.pdf).

But the deterministic physics might be interesting for physics-based games with online multiplayer (to avoid desync) or games with time-travel mechanics (so a rewinded situation has the same result). Groovy.

**Comment by rokups** [comment]
I think we can leave it open as physics should get wrapped :)

**Comment by gleblebedev** [comment]
@rokups this one could be closed now, right?

**Comment by rokups** [comment]
Yep, thanks for a reminder 🙏🏻
