### ISSUE TITLE
Segfault using AnimatedModel in MinGW build.

### ISSUE THREAD

**Issue by JTippetts** [rokups/rbfx#259]
Clean pull of rbfx, build using URHO3D_OPENGL for MinGW. Segfault occurs when running SkeletalAnimation sample. Backtrace:

#0  0x00007ff8f1f3d75c in ntdll!RtlUnwindEx () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ff8798646ba in vk_optimusGetInstanceProcAddr ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#2  0x00007ff877edd7d5 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#3  0x00007ff87809daf1 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#4  0x00007ff87809d47a in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#5  0x00007ff87809da62 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#6  0x00007ff87809d68a in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#7  0x00007ff878724774 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#8  0x00007ff878725cb6 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#9  0x00007ff87872c5d0 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#10 0x00007ff87872c9f7 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#11 0x00007ff87872a1c2 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#12 0x00007ff87873027f in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#13 0x00007ff87872f37f in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#14 0x00007ff87870d798 in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#15 0x00007ff87853ea8d in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#16 0x00007ff8786c477f in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#17 0x00007ff8786c447a in ?? ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#18 0x00007ff8789424c8 in nvoglv64!DrvValidateVersion ()
   from C:\Windows\System32\DriverStore\FileRepository\nvmi.inf_amd64_7e89df90b0b8d992\nvoglv64.dll
#19 0x00007ff8f1c77c24 in KERNEL32!BaseThreadInitThunk () from C:\Windows\System32\kernel32.dll
#20 0x00007ff8f1f8d4d1 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
#21 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by eugeneko** [comment]
Fixed in https://github.com/rokups/rbfx/commit/19c53b1930f2a0805399e128ec9e01055d83315d
