### ISSUE TITLE
Editor does not remove resource with old name from Resource Tab on file rename

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#267]
1. Add new file via FS
2. Rename it
3. Editor has both files visible

![image](https://user-images.githubusercontent.com/8576192/108908552-7cda7280-7634-11eb-9dab-5a7de5705ef4.png)

**Comment by rijx** [comment]
I had the same issue with renaming directories before, but you seem to have this problem with single files. That's unfortunate...

**Comment by rokups** [comment]
Works now. Probably got fixed along the way and we forgot to close this.
