### ISSUE TITLE
Serializable throws null exception on getter properties

### ISSUE THREAD

**Issue by Mac767** [rokups/rbfx#272]
Hello,

in "Urho3D\CSharpManaged\Scene\Serializable.cs" there is a NULL exception in line 514 for properties without setters:
        if ((property.GetMethod.IsPrivate || property.SetMethod.IsPrivate) && attribute == null)
                    continue;

In my case it was for example this property in a LogicComponent class:
        public bool IsEnabled
        {
            get
            {
                return !CurrentTarget.Equals(String.Empty);
            }
        }

My workaround at the moment is to make a method out of these properties.

**Comment by rokups** [comment]
Thanks for a report. Now properties with missing getter or setter will not be serializable as there is no point to do this.
