### ISSUE TITLE
System.ArgumentNullException: 'null string' - Component with String Property

### ISSUE THREAD

**Issue by Mac767** [rokups/rbfx#273]
Hello,

a Component with an uninitialized public string property cause a null string exception in "Urho3D\CSharp\Managed\Scene\Serializable.cs" line 284:
case VariantType.VarString:
                    dest.Set((string) _field.GetValue(ptr));

In my case this property cause the issue:
public string KeyName { get; set; }

If I modified it to "public string KeyName { get; set; } = String.Empty;" then there is no execption.

**Comment by rokups** [comment]
Thanks for a report. Now null strings are treated as empty strings. If no default value is provided - they wont even be written to saved file. 👍🏻
