### ISSUE TITLE
Missing Master/Slave

### ISSUE THREAD

**Issue by nem0** [rokups/rbfx#28]

**Comment by nem0** [comment]
I'm glad you are taking this seriously.

**Comment by nem0** [comment]
Is this dead?

**Comment by rokups** [comment]
Still have not spotted a good place where to put it, sorry :|

**Comment by rokups** [comment]
Issue was addressed [here](https://github.com/rokups/rbfx/blob/9aeec41f09b2cce6df4852c51c3c552d9642f3e2/Source/Urho3D/RmlUI/RmlUI.h#L68) and [here](https://github.com/rokups/rbfx/blob/9aeec41f09b2cce6df4852c51c3c552d9642f3e2/Source/Urho3D/CSharp/Managed/Script/RuntimeCompiledScriptPluginApplication.cs#L9).

If anyone finds this offensive please reopen the issue. When you do please make sure you are one of the following:
* Legally identified as `assembly`.
* Legally identified as `software subsystem` of any kind.

:pray:
