### ISSUE TITLE
Installation of Web SDK installs cmake/Modules and cmake/Toolchains folders to incorrect path.

### ISSUE THREAD

**Issue by JTippetts** [rokups/rbfx#290]
Building SDK for Web, in Linux subsystem for windows.

Urho3D.cmake gets installed to {install path}/share/CMake/ but the Modules/ and Toolchains/ folders get installed to {install path{/share/cmake/ due to lowercase destination path names at https://github.com/rokups/rbfx/blob/master/CMakeLists.txt#L465-L466

**Comment by rokups** [comment]
Now all files install to `share/cmake`. Yep, lowercase sucks. Thank weitjong for that :|
