### ISSUE TITLE
OpenGL doesn't build on MinGW

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#296]
1) DllMain in glew.c
2) ImGUI produces link errors
../../lib/libImGui.a(imgui_impl_opengl3.cpp.obj):img_impl_opengl3.cpp:(.text+0x1d5): undefined reference to `_imp____glewBlendEquation'

I don't know if it's shared or static build.

**Comment by gleblebedev** [comment]
![image](https://user-images.githubusercontent.com/2943937/123975522-4ed7b700-d9b5-11eb-9998-d95d05557446.png)

**Comment by eugeneko** [comment]
@rokups I think there's something messed up with ImGUI integration which leads to imgui_impl_opengl3.cpp doing some weird shit with glew

**Comment by rokups** [comment]
Did 53a4a370784093594cde5eea2fdee0ee93ef12fb / 35dba8aa193d449264faa121b52e307fe16a80f6 fix this?

**Comment by eugeneko** [comment]
Yep
