### ISSUE TITLE
c#: Check a Variant for null throws Exception

### ISSUE THREAD

**Issue by Mac767** [rokups/rbfx#308]
Hi,
please find attached sample to reproduce the behavior.

    class Program
    {
        static void Main(string[] args)
        {
            var test = new MyClass();
            test.TestFunction();
        }

        public class MyClass
        {
            public void TestFunction(Variant variant = null)
            {
                if (variant != null)
                {
                    // if throws System.StackOverflowException execption
                }
            }
        }
    }

**Comment by rokups** [comment]
Thanks 👍🏻
