### ISSUE TITLE
Texture Arrays sampling issue

### ISSUE THREAD

**Issue by JTippetts** [rokups/rbfx#312]
There is not a sample that uses Texture Arrays to verify that they are working correctly. I did a test of texture arrays at https://github.com/JTippetts/TestTextureArrays to try them out, built as a modification of the legacy terrain shader, but the array only samples black. I'm not sure if something is broken internally, or if I'm doing something wrong.

Edit: Using the OpenGL backend, MinGW build. Build settings:
-DURHO3D_GRAPHICS_API=OpenGL  -DURHO3D_STATIC_RUNTIME=1 -DBUILD_SHARED_LIBS=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "MinGW Makefiles"

Edit: Visual Studio/OpenGL build also does not work, though it samples white instead of black.

Edit: Visual Studio/D3D11 also tested, and does not work.

**Comment by eugeneko** [comment]
It took me some time to investigate, but it is actually normal Urho behaviour. OpenGL samplers should have sampler index at the end of the name. Probably should emit error if unrecognized samplers are found.

However, I have no idea why it affects D3D11 renderer... Gonna check it when it builds.

**Comment by JTippetts** [comment]
It works. Why do the default samplers in _Samplers.glsl work, when they don't have the index at the end?

**Comment by eugeneko** [comment]
Because of this thingy:
https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp#L3239

**Comment by JTippetts** [comment]
Alrighty then. Thank you.
