### ISSUE TITLE
Editor crashes when use "locate" button with asset byproduct in folder

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#320]
![image](https://user-images.githubusercontent.com/8576192/139524794-3ce98827-fba8-4408-a872-3e624a8d1585.png)
![image](https://user-images.githubusercontent.com/8576192/139524807-557c3c57-f113-45e1-8cef-06e150e9aae1.png)
![image](https://user-images.githubusercontent.com/8576192/139524813-a8bb6978-f70b-43d9-afee-88369c2df2b1.png)
![image](https://user-images.githubusercontent.com/8576192/139524824-39accfb9-5752-4c4b-a5a3-6bd33c045f5d.png)

**Comment by rokups** [comment]
Fixed in eb5d008.
