### ISSUE TITLE
Network - StaticModelGroup not repilcated

### ISSUE THREAD

**Issue by Mac767** [rokups/rbfx#379]
Hi
I tested with latest preview nuget. This should contain the new network code.
StaticModelGroup in scene were no be replicated to client.

**Comment by eugeneko** [comment]
Do you use old or new networking for Scene replication?
New networking doesn't automatically replicate things unless it's told to do it. I didn't implement the replication of StaticModelGroup specifically.
Old networking is going to be removed soon anyway.

**Comment by Mac767** [comment]
I looked into your changes in 17_SceneReplication/SceneReplication.cpp.
I did not mutch in my code so I'm on the old way.
It seems I need the NetworkBehavior stuff but this is still missing in c# like you expected.

**Comment by eugeneko** [comment]
I'll update SWIG files a bit later.
I don't really like adding stuff that I personally cannot test (I'm not C# user), so I usually just ignore C# bindings unless they are explicitly requested.

**Comment by eugeneko** [comment]
What about AdvancedNetworking sample?
I don’t remember adding any artificial delays nor I remember any specific
lags. Also, do you observe these lags with vanilla Urho?

**Comment by TrevorCash** [comment]
I removed my post because I thought it was just because low 30fps and because controls happen on server.  So my expectations were too high.  I think it is probably working ok.  AdvancedNetworking demo for me has an issue where I cant interact with the gui.

**Comment by eugeneko** [comment]
Can you please report UI issues? This UI is still WIP. Meanwhile you can
use command line arguments to run client and server, I’ll post exact lines
later if you won’t figure it out by then.

**Comment by eugeneko** [comment]
@TrevorCash okay, now I have them...
```
START build\Debug\bin\Debug\Samples.exe --pp D:\Root\Repos\Urho\rbfx\bin --sample AdvancedNetworking StartServer
START build\Debug\bin\Debug\Samples.exe --pp D:\Root\Repos\Urho\rbfx\bin --sample AdvancedNetworking Connect
```

**Comment by gleblebedev** [comment]
Rmlui issues been fixed in the latest nuget. Are you on my custom_rbfx branch?
