### ISSUE TITLE
Editor: When Scaling a node with rotation, 3DGizmo is not highlighted with the mouse correctly. 

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#39]

**Comment by rokups** [comment]
Could you make some screenshots?

**Comment by TrevorCash** [comment]
Also after I scale in the video, I press "Play".  The node does some wierd change of transform right after I hit play. - Im pretty sure this is from my physics implementation - I'll look into it.

**Comment by TrevorCash** [comment]
Yeah - Newton API was doing something wrong - that is fixed now.

**Comment by rokups** [comment]
Btw that video does not work. How about a screenshot?

**Comment by TrevorCash** [comment]
![image](https://user-images.githubusercontent.com/2559371/46671393-df309680-cb91-11e8-9000-81efae26bd1a.png)
