### ISSUE TITLE
Editor: When restoring a project sometimes the gui is messed up.

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#43]
After opening a previously saved project:
![image](https://user-images.githubusercontent.com/2559371/46834844-c549ac00-cd69-11e8-8998-808b7b2edb61.png)

**Comment by rokups** [comment]
You should really provide more information. `.ui.ini` and `.user.json` at least. Whether this is a reproducible issue or not. Any other details that could help. Screenshot alone is not much to go by..

**Comment by TrevorCash** [comment]
Here is the project that gives the issue. 
[EditorProject.zip](https://github.com/rokups/Urho3D/files/2473916/EditorProject.zip)
 It does seem project specific because it does not happen when I open another project like this one:
[EditorProject_NoBug.zip](https://github.com/rokups/Urho3D/files/2473922/EditorProject_NoBug.zip)

**Comment by TrevorCash** [comment]
The effect goes away when I delete .user.json and let it regenerate. so It seems to be related to that one.

**Comment by rokups** [comment]
Does this still happen?

**Comment by TrevorCash** [comment]
I have not had it happen on my last tests
