### ISSUE TITLE
-DURHO3D_SSE=ON Has no effect 

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#53]
(Only Tested On Windows)

I have -DURHO3D_SSE=ON in cmake: But looking at Matrix3x4.h: URHO3D_SSE is not defined:
![image](https://user-images.githubusercontent.com/2559371/47955870-e2862a80-df63-11e8-939c-7b2d1d405871.png)

**Comment by TrevorCash** [comment]
This can be fixed by removing the following "Trimming" code from the end of Urho3D.h:


```
// Disable SSE if compiler does not support it.
#if defined(URHO3D_SSE) && !defined(__SSE2__) && (!defined(_M_IX86_FP) || _M_IX86_FP < 2)
#   undef URHO3D_SSE
#endif

```

**Comment by rokups** [comment]
Relevant targets might need sse being enabled through compiler flags
