### ISSUE TITLE
Building linux without msbuild

### ISSUE THREAD

**Issue by 1Snakel** [rokups/rbfx#78]
Do I really need msbuild?

**Comment by TrevorCash** [comment]
I use QtCreator on linux with the repo - works pretty well

**Comment by 1Snakel** [comment]
well, I can build it. But to include CSharp, it's asking for msbuild.

**Comment by boberfly** [comment]
CMake lets you use NMake, Jom, Ninja if you prefer by specifying those generators instead.

**Comment by 1Snakel** [comment]
![image](https://user-images.githubusercontent.com/11818756/57204069-8be9bf80-6f8b-11e9-977d-3e2c30d5faba.png)
why msbuild, and not xbuild... wait, it's probably due to mono version.

**Comment by rokups** [comment]
Yes and no. Msbuild is used for building c# part. It runs fine on Linux and 
macos. But if you build without c# then msbuild is not needed at all.

**Comment by rokups** [comment]
BTW xbuild is deprecated and official msbuild runs on Linux now. Mono 
website has a download I think. Distros also usually package it nowadays

**Comment by 1Snakel** [comment]
mine dosen't, well thanks for the i
