### ISSUE TITLE
Fixed Update Rate Option For Engine

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#80]
Sometimes its nice to have a fixed update rate instead of specifying min and max fps.  This is especially true if you want accurate physics.  physics engines require update rates that are constants.  I have been running on modified Engine code that uses fixed timing for a long time now.

**Comment by TrevorCash** [comment]
Ideally There would be a seperate Update rate and a separate Render Rate. the Update Rate could be held constant while the Render Rate could fluctuate - Interpolating between previous and current sets of node transforms. But that's more of an engine rework.

**Comment by rokups** [comment]
Could you link to your fixed timing implementation? This could be useful as optional addon if it does not break/alter existing features (if it can be reliable).

**Comment by TrevorCash** [comment]
It was a pretty simple change that I had, But  not sure how it would be an addons as it was some changes to Engine.cpp.  it didn't break any features for me.  I'll look into it.

**Comment by rokups** [comment]
If it is [this](https://github.com/TrevorCash/Urho3D/commit/8c773a42a9539b2f9cf5c3e76b7d572cc6b6b4fa#diff-49bca172f0639e313df34ce2741de7e0) commit - it would cause simulation slowdown when framerate drops.

**Comment by TrevorCash** [comment]
Yeah that's the commit. When the framerates drops, I dont see how it would behalve any different than the original implementation.  All update handles still get the delta time step as a parameter so simulation logic that scales by time step would still work.  Essentially that commit just schedules update and render events off of a fixed time interval.

**Comment by rokups** [comment]
That does not sound right. `timeStep_` is always constant and it is passed to all events to use as simulation delta. Even in extreme cases when update/render takes for example 1000s - all objects will be simulated as if 16ms passed. As a result everything will run at slow motion.

**Comment by TrevorCash** [comment]
But once the time step is not constant it should be more "stable" from the way timing is reworked.  Thus keeping any timing for other systems more stable

**Comment by rokups** [comment]
Alright, but if timestep is not constant then update no longer runs at fixed rate.

**Comment by TrevorCash** [comment]
The time step variable will not be constant in programming terms.  But may fluctuate by vary small amounts.  The timing logic that drives and sets the time step variable will make it a goal to keep the time as constant as possible.

**Comment by rokups** [comment]
Since this is not exactly trivial to achieve i dont see it happening. Besides benefit is questionable, so closing.
