### ISSUE TITLE
Makefile.cmd

### ISSUE THREAD

**Issue by Zamir7** [rokups/rbfx#82]
In Makefile.cmd  msbuild Urho3D.sln /t:restore
Urho3D.sln renamed to Urho3D.part.sln

And next error on build:
```
Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works 
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done 
-- Detecting CXX compile features 
-- Detecting CXX compile features - done 
CMake Error at CMake/Modules/UrhoCommon.cmake:350 (message): 
  sn coild not be found. 
Call Stack (most recent call first): 
  CMakeLists.txt:36 (include)
```

**Comment by rokups** [comment]
Are you sure you have C# stuff for visual studio installed?

**Comment by Zamir7** [comment]
Yes

**Comment by rokups** [comment]
Can you run `sn.exe` from vs2019 command line?

**Comment by Zamir7** [comment]
no(

**Comment by Zamir7** [comment]
For some reason, many commands are not invoked with cmd, for example, msbuild, i have to specify the full path

**Comment by rokups** [comment]
I think you dont have all needed stuff installed. Checking "C# Desktop Development" is a good bet. Make sure you install 4.7.1 framework too.

As for commands - you need to set up needed environment (for example) by running

> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

Then running `msbuild` will work. `Makefile.cmd` does all that automatically though.

**Comment by Zamir7** [comment]
> I think you dont have all needed stuff installed
On the contrary, I only recently installed C++, I program myself with C#

**Comment by rokups** [comment]
![sn](https://user-images.githubusercontent.com/19151258/57786932-175a1200-773d-11e9-883c-2ee74219d454.png)
It is here for me. Find out whatever package you are missing and install via VS installer. I am not sure which one it is.

**Comment by Zamir7** [comment]
i have to NETFX 4.7.2 Tools, install  NETFX 4.7.1?

**Comment by rokups** [comment]
Try it. Atm 4.7.1 is hardcoded in multiple places.

**Comment by Zamir7** [comment]
wich of MSbuild?
![1](https://user-images.githubusercontent.com/8374434/57794367-21374180-774c-11e9-95fa-1d719d95166f.jpg)

**Comment by rokups** [comment]
Do not run msbuild by specifying full path. Run whatever one starts by 
typing "msbuild"

**Comment by Zamir7** [comment]
so does not find (

**Comment by rokups** [comment]
Run it from visual studio command prompt (shortcut in start menu)

**Comment by Zamir7** [comment]
I try, not find...

**Comment by Zamir7** [comment]
I have Vs 2019, not Vs 2017...

**Comment by Zamir7** [comment]
A friend wrote, "Everything is going to ... like ... under Vs 2017. And under 2019 it swears that it is not in the build script of its support."

**Comment by Zamir7** [comment]
It's Ok!

**Comment by rokups** [comment]
Figured it out?

**Comment by Zamir7** [comment]
My mistake... sorry
