### ISSUE TITLE
C# matrices are row-major while c++ ones are column-major

### ISSUE THREAD

**Issue by rokups** [rokups/rbfx#85]
Both OpenTK and `System.Numerics.Vectors` matrices are row-major. It would be convenient to use `System.Numerics.Vectors` matrices due to simd support. We most likely should just drop OpenTK math libraries and do a straight port of C++ vector/matrix/quaternion classes and add simd support when possible ourselves.

**Comment by amerkoleci** [comment]
Note that urho3d Quaternion is w, x, y, z while C# ones x, y, z, w
