### ISSUE TITLE
Color params in materials not showing color picker

### ISSUE THREAD

**Issue by dragonCASTjosh** [rokups/rbfx#96]
When editing material paramaters i noticed that diffuse color and other color values are just shown as vec4 in imgui and not colors. 

Id recommend changing it to a color picker. (i had a look but so far iv not been able to work out where it gets the imgui code from for inspector windows)

**Comment by rokups** [comment]
It's in editor project, MaterialInspectot or similar. You can open 
InspectorTab, put a breakpoint on rendering method call and step in

**Comment by rokups** [comment]
This was fixed a while back.
