### ISSUE TITLE
Cant compile c# bindings on w10 vs2017

### ISSUE THREAD

**Issue by kororro** [rokups/rbfx#97]
I can't compile C# bindings with VS2017 community on w10 64bit.
C++ samples works right. I have newest mono installed.

Tried 2 different ways:
1. started cmake-gui, checked URHO3D_CSHARP, setting manually MSBUILD and SN directories to C:\Program Files\Mono\bin  and then generate .sln and compiled, got errors.
2. started Developer Command Prompt for VS 2017 and started cmake-gui, checked URHO3D_CSHARP, and generated .sln and compiled, got same errors.

![error](https://user-images.githubusercontent.com/42260382/59440418-9ce5e600-8dff-11e9-80c1-cd11799e8ffd.png)

**Comment by rokups** [comment]
Mono is not exactly supported on windows. Install .net framework 4.7.1 and use that. If you insist on using Mono we will gladly accept PRs that fix the build :]

**Comment by kororro** [comment]
When used (2) Developer Command Prompt for VS 2017, it uses .net 4.7.1.
Tried
  F:\CS_CPP\rbfx\build2>msbuild /t:restore ./Urho3D.sln
ont know what this did but now c# bindings works, thanks :)

Solved.

**Comment by rokups** [comment]
> don't know what this did but now c# bindings works

It restores nuget packages. C# ecosystem madness \o/
